from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Any, Tuple
import pandas as pd
from dash import dcc

class ExportCommand(ABC):
    @abstractmethod
    def execute(self, df: pd.DataFrame, chart_id: str) -> Any:
        pass

class CSVExport(ExportCommand):
    def execute(self, df: pd.DataFrame, chart_id: str) -> Any:
        return dcc.send_data_frame(df.to_csv, f"{chart_id}_export.csv")

class MarkdownExport(ExportCommand):
    def execute(self, df: pd.DataFrame, chart_id: str) -> Any:
        content = f"# Export: {chart_id}\n\n## Data Preview\n\n" + df.head(10).to_markdown()
        return dict(content=content, filename=f"{chart_id}_report.md")

class PythonExport(ExportCommand):
    def execute(self, df: pd.DataFrame, chart_id: str) -> Any:
        content = f"import pandas as pd\n# Autogenerated Snippet for {chart_id}\ndf = pd.read_csv('{chart_id}_export.csv')\nprint(df.describe())"
        return dict(content=content, filename=f"{chart_id}_script.py")

class ExportRegistry:
    """Industrial registry for export commands."""
    def __init__(self):
        self.commands = {
            "csv": CSVExport(),
            "md": MarkdownExport(),
            "py": PythonExport()
        }

    def register(self, mode: str, command: ExportCommand):
        """Register a new export command."""
        self.commands[mode] = command

    def get_command(self, export_type: str) -> ExportCommand | None:
        return self.commands.get(export_type.lower())

    def export(self, export_type: str, df: pd.DataFrame, chart_id: str) -> Any:
        cmd = self.get_command(export_type)
        if cmd:
            return cmd.execute(df, chart_id)
        return None
