services:
  manhattanmissioncontrol:
    image: manhattanmissioncontrol
    build:
      context: desktop
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8501:8501
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "main.js"]
