services:
  manhattanmissioncontrol:
    image: manhattanmissioncontrol
    build:
      context: desktop
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8501:8501
