from __future__ import annotations

from typing import Iterable


def build_fts_index_sql(table: str, columns: Iterable[str], language: str = "english", index_name: str | None = None) -> str:
    """Return SQL to create a GIN-backed FTS expression index on `table` for `columns`.

    The generated index uses `to_tsvector(language, concat(cols))` as an expression index.
    """
    cols = list(columns)
    if not cols:
        raise ValueError("columns must be a non-empty iterable of column names")
    concat = " || ' ' || ".join(f"COALESCE({c}, '')" for c in cols)
    safe_table = table.replace('"', '')
    safe_cols = "_".join(c.replace('"', '').replace('.', '_') for c in cols)
    idx = index_name or f"{safe_table.replace('.', '_')}_{safe_cols}_fts_idx"
    sql = f"CREATE INDEX IF NOT EXISTS \"{idx}\" ON {table} USING GIN (to_tsvector('{language}', {concat}));"
    return sql


def ensure_fts_index(dsn: str, table: str, columns: Iterable[str], language: str = "english") -> None:
    """Connect to Postgres and create the FTS index for the given table/columns.

    This is a convenience helper that executes the SQL generated by `build_fts_index_sql`.
    """
    try:
        import psycopg
    except Exception as exc:
        raise ImportError("Install Postgres extras: pip install '.[postgres]'") from exc
    sql = build_fts_index_sql(table, columns, language=language)
    conn = psycopg.connect(dsn)
    cur = conn.cursor()
    cur.execute(sql)
    conn.commit()
    conn.close()
