#!/usr/bin/env python3
"""
retro_runner.py — Interactive CLI to fill in a retrospective template for an NYC DOT analysis.

Usage:
    python retro_runner.py --project "Q1 2026 Ramp SLA Audit" --out retro_q1_ramp.md
    python retro_runner.py --project "Violation Trend MN" --framework 4ls --out retro_viol_mn.md

The script prompts for key inputs interactively and produces a completed markdown file
that can be filed alongside the analysis artifacts.
"""

from __future__ import annotations

import argparse
import sys
from datetime import date
from pathlib import Path


def prompt(label: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    value = input(f"{label}{suffix}: ").strip()
    return value if value else default


def prompt_multiline(label: str) -> list[str]:
    print(f"{label} (enter blank line to finish):")
    lines: list[str] = []
    while True:
        line = input("  > ").strip()
        if not line:
            break
        lines.append(line)
    return lines


def collect_issues() -> list[dict]:
    issues: list[dict] = []
    while True:
        print(f"\n  Issue {len(issues) + 1} (leave problem blank to stop):")
        problem = prompt("    Problem observed", "")
        if not problem:
            break
        whys: list[str] = []
        for i in range(1, 4):
            w = prompt(f"    Why {i}", "")
            if not w:
                break
            whys.append(w)
        action = prompt("    Action item (owner: due)", "TBD: TBD")
        issues.append({"problem": problem, "whys": whys, "action": action})
    return issues


def render(
    project: str,
    framework: str,
    wells: list[str],
    issues: list[dict],
    learnings: list[str],
    today: date,
) -> str:
    issue_blocks = []
    for i, iss in enumerate(issues, 1):
        why_lines = "\n".join(f"- Why {j + 1}: {w}" for j, w in enumerate(iss["whys"]))
        block = (
            f"### Issue {i}\n\n"
            f"**Observed problem:** {iss['problem']}\n\n"
            f"**Root cause (5-whys):**\n{why_lines}\n\n"
            f"**Action item:** {iss['action']}"
        )
        issue_blocks.append(block)

    wells_block = "\n".join(f"{i}. {w}" for i, w in enumerate(wells, 1)) or "1. <!-- add -->"
    learnings_block = "\n".join(f"- {l}" for l in learnings) or "- <!-- add -->"
    issues_block = (
        "\n\n".join(issue_blocks)
        if issue_blocks
        else "### Issue 1\n\n**Observed problem:** <!-- add -->\n"
    )

    return f"""# Analysis Retrospective

**Project:** {project}
**Completed:** {today}
**Retrospective date:** {today}
**Participants:** <!-- names -->
**Framework used:** {framework.upper()}

---

## Project summary

<!-- 2 sentences: what was delivered and to whom. -->

---

## What went well

{wells_block}

---

## What had problems

{issues_block}

---

## Learnings for the team

{learnings_block}

---

## Action items

| # | Action | Owner | Due | Status |
|---|---|---|---|---|
| 1 | <!-- from issues above --> | | | OPEN |

---

## Data and methodology notes

- Dataset issues discovered: <!-- fill in -->
- Column definition surprises: <!-- fill in -->
- Performance notes: <!-- fill in -->

---

_Generated by retro_runner.py on {today}_
"""


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Interactively generate an analysis retrospective document."
    )
    parser.add_argument("--project", required=True, help="Short project name")
    parser.add_argument(
        "--framework",
        choices=["ssc", "4ls"],
        default="ssc",
        help="Framework: ssc=Start/Stop/Continue, 4ls=4Ls",
    )
    parser.add_argument("--out", default="", help="Output file path (default: print to stdout)")
    parser.add_argument(
        "--non-interactive", action="store_true", help="Skip prompts, produce empty template"
    )
    args = parser.parse_args()

    today = date.today()

    if args.non_interactive:
        wells: list[str] = ["<!-- add -->", "<!-- add -->"]
        issues: list[dict] = []
        learnings: list[str] = ["<!-- add -->"]
    else:
        print(f"\nRetrospective for: {args.project}")
        print("=" * 50)

        print("\n[What went well — enter at least 2 items]")
        wells = prompt_multiline("What went well")
        if len(wells) < 2:
            wells += ["<!-- add more -->"] * (2 - len(wells))

        print("\n[Problems with root cause — press Enter to skip an issue]")
        issues = collect_issues()

        print("\n[Learnings for the team — one per line, blank to finish]")
        learnings = prompt_multiline("Learnings")

    output = render(args.project, args.framework, wells, issues, learnings, today)

    if args.out:
        Path(args.out).write_text(output, encoding="utf-8")
        print(f"Retrospective written to: {args.out}", file=sys.stderr)
    else:
        print(output)


if __name__ == "__main__":
    main()
