"""Generate visualization_callbacks.py from DATASET_REGISTRY.yaml."""

from __future__ import annotations

import logging
from pathlib import Path
from textwrap import dedent
from typing import Any

logger = logging.getLogger(__name__)


class CallbackGenerator:
    """Generates Dash callbacks from registry."""

    def __init__(self, registry: dict[str, Any]):
        """Initialize callback generator.

        Args:
            registry: Parsed DATASET_REGISTRY.yaml
        """
        self.registry = registry
        self.datasets = registry.get("datasets", {})

    def generate(self) -> str:
        """Generate visualization_callbacks.py.

        Returns:
            Path to generated file
        """
        output_path = Path(self.registry["generators"]["output_paths"]["callbacks"])
        output_path.parent.mkdir(parents=True, exist_ok=True)

        code = self._generate_module_header()
        code += self._generate_callback_factory_class()
        code += self._generate_dataset_callbacks()

        with open(output_path, "w") as f:
            f.write(code)

        logger.info(f"Generated callbacks module: {output_path}")
        return str(output_path)

    def _generate_module_header(self) -> str:
        """Generate module docstring and imports."""
        return dedent('''
            """Auto-generated Dash callbacks from DATASET_REGISTRY.yaml.

            This module is generated by CodegenFramework.generate_callbacks().
            DO NOT EDIT MANUALLY — regenerate from registry instead.

            Pattern:
                Each dataset gets a standard callback:
                @callback(
                    Output(f"chart-{dataset_key}", "figure"),
                    Output(f"narrative-{dataset_key}", "children"),
                    Input("store-global-filters", "data"),
                    prevent_initial_call=True,
                )
                def update_chart_callback(filters):
                    # Fetch data
                    # Calculate KPIs
                    # Render figure + narrative
                    return fig, narrative

            Usage:
                from app.callbacks.generated.visualization_callbacks import CallbackFactory

                factory = CallbackFactory()
                factory.register_all_callbacks()
            """

            from __future__ import annotations

            import logging
            from typing import Any

            from dash import Input, Output, callback, html

            logger = logging.getLogger(__name__)


            class CallbackFactory:
                """Factory for generating Dash callbacks."""

                def __init__(self):
                    """Initialize factory."""
                    pass

                def register_all_callbacks(self) -> None:
                    """Register all dataset callbacks."""
                    logger.info("Auto-generated callbacks registered from DATASET_REGISTRY")

                def create_chart_callback(
                    self,
                    dataset_key: str,
                    dataset_config: dict[str, Any],
                ) -> None:
                    """Create and register callback for dataset.

                    Args:
                        dataset_key: Dataset identifier (e.g., "inspection")
                        dataset_config: Dataset configuration from registry
                    """
                    logger.debug(f"Creating callback for dataset: {dataset_key}")

        ''')

    def _generate_callback_factory_class(self) -> str:
        """Generate CallbackFactory methods."""
        return ""  # Included in header

    def _generate_dataset_callbacks(self) -> str:
        """Generate callback functions for datasets."""
        code = "\n# ============================================================================\n"
        code += "# Dataset-Specific Callbacks\n"
        code += "# ============================================================================\n\n"

        active_datasets = {
            k: v
            for k, v in self.datasets.items()
            if v.get("status") == "active"
        }

        for key, dataset in sorted(active_datasets.items()):
            code += self._generate_dataset_callback(key, dataset)
            code += "\n"

        return code

    def _generate_dataset_callback(self, key: str, dataset: dict[str, Any]) -> str:
        """Generate callback for single dataset.

        Args:
            key: Dataset key
            dataset: Dataset config

        Returns:
            Python callback code
        """
        callback_name = f"update_{key}_chart"
        kpis = dataset.get("kpis", [])
        kpi_list = ", ".join(f'"{kpi}"' for kpi in kpis) if kpis else "# No KPIs"

        code = dedent(f'''
            @callback(
                Output("chart-{key}", "figure"),
                Output("narrative-{key}", "children"),
                Input("store-global-filters", "data"),
                prevent_initial_call=True,
            )
            def {callback_name}(filters: dict[str, Any]):
                """Update chart and narrative for {dataset["name"]}.

                Data flow:
                    1. Fetch from MotherDuck view ({dataset["fourfour"]})
                    2. Apply user filters
                    3. Calculate KPIs: {kpi_list}
                    4. Render Plotly figure + insight narrative
                    5. Return (fig, narrative_html)

                Args:
                    filters: Global filter dictionary from store

                Returns:
                    Tuple of (Figure, narrative_html)
                """
                try:
                    # TODO: Implement data fetch from MotherDuck
                    # df = fetch_motherduck("{key}", filters)

                    # TODO: Calculate KPIs
                    # kpi_results = compute_kpis(df, kpis=[{kpi_list}])

                    # TODO: Create figure
                    # from socrata_toolkit.codegen.generated.plotly_charts import {key}_chart
                    # fig = {key}_chart(df)

                    # TODO: Generate narrative
                    # narrative = f"<p>Placeholder narrative for {key}</p>"

                    # return fig, narrative
                    return {{}}, html.Div("Callback implementation pending")

                except Exception as e:
                    logger.error(f"Error in {callback_name}: {{e}}")
                    return {{}}, html.Div(f"Error: {{str(e)}}")

        ''')

        return code
