"""Generate plotly_charts.py functions from DATASET_REGISTRY.yaml."""

from __future__ import annotations

import logging
from pathlib import Path
from textwrap import dedent
from typing import Any

logger = logging.getLogger(__name__)


class ChartGenerator:
    """Generates chart factory functions from registry."""

    def __init__(self, registry: dict[str, Any]):
        """Initialize chart generator.

        Args:
            registry: Parsed DATASET_REGISTRY.yaml
        """
        self.registry = registry
        self.datasets = registry.get("datasets", {})
        self.defaults = registry.get("defaults", {})

    def generate(self) -> str:
        """Generate plotly_charts.py.

        Returns:
            Path to generated file
        """
        output_path = Path(self.registry["generators"]["output_paths"]["charts"])
        output_path.parent.mkdir(parents=True, exist_ok=True)

        code = self._generate_module_header()
        code += self._generate_chart_factory_class()
        code += self._generate_dataset_chart_functions()

        with open(output_path, "w") as f:
            f.write(code)

        logger.info(f"Generated charts module: {output_path}")
        return str(output_path)

    def _generate_module_header(self) -> str:
        """Generate module docstring and imports."""
        return dedent('''
            """Auto-generated Plotly chart functions from DATASET_REGISTRY.yaml.

            This module is generated by CodegenFramework.generate_charts().
            DO NOT EDIT MANUALLY — regenerate from registry instead.

            Generated functions:
            - ChartFactory.create() — Universal chart creation method
            - Dataset-specific chart functions (e.g., inspection_chart, violations_chart)

            Usage:
                from socrata_toolkit.codegen.generated.plotly_charts import ChartFactory

                factory = ChartFactory()
                fig = factory.create("inspection", df, iv="borough", dv="violation_count")

                # Or use dataset-specific function:
                from socrata_toolkit.codegen.generated.plotly_charts import inspection_chart
                fig = inspection_chart(df)
            """

            from __future__ import annotations

            import logging
            from typing import Any, Optional

            import pandas as pd

            logger = logging.getLogger(__name__)


            class ChartSpec:
                """Specification for chart generation."""

                def __init__(
                    self,
                    chart_type: str,
                    data: pd.DataFrame,
                    iv_column: str,
                    dv_column: str,
                    title: str,
                    colors: dict[str, str] | None = None,
                    aggregation: str = "count",
                    limit: int | None = None,
                ):
                    """Initialize chart spec.

                    Args:
                        chart_type: Type of chart (bar, line, heatmap, etc.)
                        data: DataFrame to visualize
                        iv_column: Independent variable column name
                        dv_column: Dependent variable column name
                        title: Chart title
                        colors: Color mapping (optional)
                        aggregation: Aggregation function (sum, mean, count, etc.)
                        limit: Maximum records to display (optional)
                    """
                    self.chart_type = chart_type
                    self.data = data
                    self.iv_column = iv_column
                    self.dv_column = dv_column
                    self.title = title
                    self.colors = colors or {}
                    self.aggregation = aggregation
                    self.limit = limit


            class ChartFactory:
                """Factory for creating Plotly figures from specifications."""

                def __init__(self):
                    """Initialize factory."""
                    try:
                        import plotly.graph_objects as go
                        import plotly.express as px

                        self.go = go
                        self.px = px
                    except ImportError as exc:
                        raise ImportError(
                            "Install plotly: pip install plotly"
                        ) from exc

                def create(self, spec: ChartSpec) -> Any:
                    """Create Plotly figure from specification.

                    Args:
                        spec: ChartSpec object

                    Returns:
                        plotly.graph_objects.Figure

                    Raises:
                        ValueError: If chart_type unsupported
                    """
                    method_name = f"_create_{spec.chart_type}"
                    if not hasattr(self, method_name):
                        raise ValueError(
                            f"Unsupported chart type: {spec.chart_type}"
                        )

                    method = getattr(self, method_name)
                    return method(spec)

                def _create_vertical_bar(self, spec: ChartSpec) -> Any:
                    """Create vertical bar chart."""
                    agg_df = (
                        spec.data.groupby(spec.iv_column)[spec.dv_column]
                        .agg(spec.aggregation)
                        .reset_index()
                    )
                    agg_df = agg_df.sort_values(spec.dv_column, ascending=False)
                    if spec.limit:
                        agg_df = agg_df.head(spec.limit)

                    fig = self.go.Figure(
                        self.go.Bar(
                            x=agg_df[spec.iv_column],
                            y=agg_df[spec.dv_column],
                            text=agg_df[spec.dv_column],
                            textposition="auto",
                        )
                    )
                    fig.update_layout(title=spec.title, template="plotly_white")
                    return fig

                def _create_horizontal_bar(self, spec: ChartSpec) -> Any:
                    """Create horizontal bar chart."""
                    agg_df = (
                        spec.data.groupby(spec.iv_column)[spec.dv_column]
                        .agg(spec.aggregation)
                        .reset_index()
                    )
                    agg_df = agg_df.sort_values(spec.dv_column, ascending=True)
                    if spec.limit:
                        agg_df = agg_df.head(spec.limit)

                    fig = self.go.Figure(
                        self.go.Bar(
                            y=agg_df[spec.iv_column],
                            x=agg_df[spec.dv_column],
                            text=agg_df[spec.dv_column],
                            textposition="auto",
                            orientation="h",
                        )
                    )
                    fig.update_layout(title=spec.title, template="plotly_white")
                    return fig

                def _create_line(self, spec: ChartSpec) -> Any:
                    """Create line chart."""
                    agg_df = (
                        spec.data.groupby(spec.iv_column)[spec.dv_column]
                        .agg(spec.aggregation)
                        .reset_index()
                    )
                    agg_df = agg_df.sort_values(spec.iv_column)

                    fig = self.go.Figure(
                        self.go.Scatter(
                            x=agg_df[spec.iv_column],
                            y=agg_df[spec.dv_column],
                            mode="lines+markers",
                            fill="tozeroy",
                        )
                    )
                    fig.update_layout(title=spec.title, template="plotly_white")
                    return fig

                def _create_stacked_bar(self, spec: ChartSpec) -> Any:
                    """Create stacked bar chart."""
                    fig = self.px.bar(
                        spec.data,
                        x=spec.iv_column,
                        y=spec.dv_column,
                        title=spec.title,
                    )
                    fig.update_layout(template="plotly_white")
                    return fig

                def _create_choropleth(self, spec: ChartSpec) -> Any:
                    """Create choropleth map (requires geometry)."""
                    fig = self.go.Figure()
                    fig.add_annotation(
                        text="Choropleth charts require GeoDataFrame and geometry column"
                    )
                    return fig

        ''')

    def _generate_chart_factory_class(self) -> str:
        """Generate ChartFactory helper methods."""
        return ""  # Included in header

    def _generate_dataset_chart_functions(self) -> str:
        """Generate dataset-specific chart functions."""
        code = "\n# ============================================================================\n"
        code += "# Dataset-Specific Chart Functions\n"
        code += "# ============================================================================\n\n"

        active_datasets = {
            k: v
            for k, v in self.datasets.items()
            if v.get("status") == "active"
        }

        for key, dataset in sorted(active_datasets.items()):
            if not dataset.get("visualization"):
                continue

            code += self._generate_dataset_function(key, dataset)
            code += "\n"

        return code

    def _generate_dataset_function(self, key: str, dataset: dict[str, Any]) -> str:
        """Generate chart function for single dataset.

        Args:
            key: Dataset key
            dataset: Dataset config

        Returns:
            Python function code
        """
        viz = dataset.get("visualization", {})
        chart_type = viz.get("default_chart", "vertical_bar")
        iv_col = viz.get("iv_column")
        dv_col = viz.get("dv_column")
        title = viz.get("title_template", dataset["name"])
        colors = viz.get("colors", {})

        func_name = f"{key}_chart"

        code = dedent(f'''
            def {func_name}(
                df: pd.DataFrame,
                title: str | None = None,
                aggregation: str = "{viz.get("aggregation", "count")}",
            ) -> Any:
                """Create chart for {dataset["name"]} ({dataset["fourfour"]}).

                Args:
                    df: Data frame with columns from {dataset["fourfour"]}
                    title: Override default title (optional)
                    aggregation: Aggregation function (default: {viz.get("aggregation", "count")})

                Returns:
                    plotly.graph_objects.Figure
                """
                spec = ChartSpec(
                    chart_type="{chart_type}",
                    data=df,
                    iv_column="{iv_col}",
                    dv_column="{dv_col}",
                    title=title or "{title}",
                    aggregation=aggregation,
                )
                factory = ChartFactory()
                return factory.create(spec)

        ''')

        return code
