"""Generate markdown documentation from DATASET_REGISTRY.yaml."""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


class DocsGenerator:
    """Generates markdown documentation from registry."""

    def __init__(self, registry: dict[str, Any]):
        """Initialize docs generator.

        Args:
            registry: Parsed DATASET_REGISTRY.yaml
        """
        self.registry = registry
        self.datasets = registry.get("datasets", {})
        self.metadata = registry.get("registry_metadata", {})

    def generate(self) -> str:
        """Generate markdown documentation.

        Returns:
            Path to generated file
        """
        output_path = Path(self.registry["generators"]["output_paths"]["docs"])
        output_path.parent.mkdir(parents=True, exist_ok=True)

        doc = self._generate_header()
        doc += self._generate_summary()
        doc += self._generate_datasets_by_category()
        doc += self._generate_kpi_reference()
        doc += self._generate_archived_notice()

        with open(output_path, "w") as f:
            f.write(doc)

        logger.info(f"Generated documentation: {output_path}")
        return str(output_path)

    def _generate_header(self) -> str:
        """Generate markdown header."""
        return (
            f"""---
title: Dataset Registry Documentation (Auto-Generated)
version: {self.metadata.get('version', '1.0')}
status: AUTO_GENERATED
created: {self.metadata.get('last_updated', 'unknown')}
source: DATASET_REGISTRY.yaml
---

# Complete Dataset Registry — Auto-Generated from DATASET_REGISTRY.yaml

**NOTE:** This documentation is auto-generated by `CodegenFramework.generate_docs()`.
DO NOT EDIT MANUALLY — regenerate from registry instead.

---

## Summary

- **Total Datasets:** {self.metadata.get('total_datasets', 0)}
- **Active Datasets:** {self.metadata.get('active_datasets', 0)}
- **Archived Datasets:** {self.metadata.get('archived_datasets', 0)}
- **Domain:** {self.metadata.get('domain', 'data.cityofnewyork.us')}
- **Last Updated:** {self.metadata.get('last_updated', 'unknown')}

---

"""
        )

    def _generate_summary(self) -> str:
        """Generate summary table of all datasets."""
        doc = "## All Datasets\n\n"
        doc += "| Key | Name | Status | Frequency | Rows | Quality |\n"
        doc += "|-----|------|--------|-----------|------|----------|\n"

        for key in sorted(self.datasets.keys()):
            ds = self.datasets[key]
            status = ds.get("status", "unknown")
            freq = ds.get("frequency", "unknown")
            rows = ds.get("estimated_rows", "unknown")
            quality = ds.get("quality_score", "unknown")

            doc += f"| `{key}` | {ds.get('name', 'Unknown')} | {status} | {freq} | {rows} | {quality} |\n"

        doc += "\n"
        return doc

    def _generate_datasets_by_category(self) -> str:
        """Generate datasets organized by category/tag."""
        doc = "## Datasets by Category\n\n"

        # Collect all tags
        all_tags = set()
        for ds in self.datasets.values():
            all_tags.update(ds.get("tags", []))

        for tag in sorted(all_tags):
            doc += f"### {tag.replace('_', ' ').title()}\n\n"

            datasets_with_tag = {
                k: v
                for k, v in self.datasets.items()
                if tag in v.get("tags", [])
            }

            for key in sorted(datasets_with_tag.keys()):
                ds = datasets_with_tag[key]
                fourfour = ds.get("fourfour", "unknown")
                status = ds.get("status", "")

                if status == "archived":
                    doc += f"- ~~{ds['name']}~~ (DEPRECATED) — `{fourfour}`\n"
                else:
                    kpis = ds.get("kpis", [])
                    kpi_str = f" | KPIs: {', '.join(kpis)}" if kpis else ""
                    doc += f"- **{ds['name']}** — `{fourfour}`{kpi_str}\n"

            doc += "\n"

        return doc

    def _generate_kpi_reference(self) -> str:
        """Generate KPI reference section."""
        doc = "## KPI Reference\n\n"
        doc += "KPIs mapped to datasets that feed them:\n\n"

        # Collect all KPIs
        all_kpis = {}
        for key, ds in self.datasets.items():
            for kpi in ds.get("kpis", []):
                if kpi not in all_kpis:
                    all_kpis[kpi] = []
                all_kpis[kpi].append(key)

        for kpi in sorted(all_kpis.keys()):
            dataset_keys = all_kpis[kpi]
            doc += f"- **{kpi}** — datasets: {', '.join(f'`{k}`' for k in dataset_keys)}\n"

        doc += "\n"
        return doc

    def _generate_archived_notice(self) -> str:
        """Generate archived datasets notice."""
        archived = {
            k: v
            for k, v in self.datasets.items()
            if v.get("status") == "archived"
        }

        if not archived:
            return ""

        doc = "## Archived Datasets ⚠️\n\n"
        doc += "The following datasets are no longer maintained. Do not use in new analyses.\n\n"

        for key in sorted(archived.keys()):
            ds = archived[key]
            doc += f"### {ds['name']}\n\n"
            doc += f"- **Fourfour:** `{ds.get('fourfour', 'unknown')}`\n"
            doc += f"- **Reason:** {ds.get('notes', 'Unknown')}\n"
            doc += f"- **Last Updated:** {ds.get('last_updated', 'Unknown')}\n"
            doc += "\n"

        return doc
