"""Generate KPI calculation stubs from DATASET_REGISTRY.yaml."""

from __future__ import annotations

import logging
from pathlib import Path
from textwrap import dedent
from typing import Any

logger = logging.getLogger(__name__)


class KPIGenerator:
    """Generates KPI calculation stubs from registry."""

    def __init__(self, registry: dict[str, Any]):
        """Initialize KPI generator.

        Args:
            registry: Parsed DATASET_REGISTRY.yaml
        """
        self.registry = registry
        self.datasets = registry.get("datasets", {})

    def generate(self) -> str:
        """Generate KPI calculation stubs.

        Returns:
            Path to generated file
        """
        output_path = Path(self.registry["generators"]["output_paths"]["kpis"])
        output_path.parent.mkdir(parents=True, exist_ok=True)

        code = self._generate_module_header()
        code += self._generate_kpi_engine_class()
        code += self._generate_kpi_stubs()

        with open(output_path, "w") as f:
            f.write(code)

        logger.info(f"Generated KPI stubs: {output_path}")
        return str(output_path)

    def _generate_module_header(self) -> str:
        """Generate module docstring and imports."""
        return dedent('''
            """Auto-generated KPI calculation stubs from DATASET_REGISTRY.yaml.

            This module is generated by CodegenFramework.generate_kpis().
            DO NOT EDIT MANUALLY — regenerate from registry instead.

            Generated stubs define calculation signatures for all KPIs in registry.
            Implement each @kpi decorated function to complete the integration.

            Usage:
                from socrata_toolkit.codegen.generated.kpi_stubs import KPIEngine

                engine = KPIEngine()
                result = engine.compute("inspection", "inspections_scheduled_week", {})
            """

            from __future__ import annotations

            import logging
            from dataclasses import dataclass
            from typing import Any, Optional

            import pandas as pd

            logger = logging.getLogger(__name__)


            @dataclass
            class KPIResult:
                """Result of KPI computation."""

                kpi_name: str
                dataset_key: str
                value: float | int | str
                unit: str
                timestamp: str
                freshness_days: int | None = None
                metadata: dict[str, Any] | None = None


            class KPIEngine:
                """Compute KPIs from datasets."""

                def __init__(self):
                    """Initialize KPI engine."""
                    self.computed = {}

                def compute(
                    self,
                    dataset_key: str,
                    kpi_name: str,
                    filters: dict[str, Any] | None = None,
                ) -> KPIResult:
                    """Compute KPI from dataset.

                    Args:
                        dataset_key: Dataset identifier (e.g., "inspection")
                        kpi_name: KPI identifier (e.g., "inspections_scheduled_week")
                        filters: Optional filter dictionary

                    Returns:
                        KPIResult with computed value

                    Raises:
                        ValueError: If dataset or KPI not found
                    """
                    if filters is None:
                        filters = {}

                    key = f"{dataset_key}:{kpi_name}"
                    method_name = f"compute_{key.replace(':', '_')}"

                    if not hasattr(self, method_name):
                        raise ValueError(
                            f"KPI not found: {dataset_key}:{kpi_name}"
                        )

                    method = getattr(self, method_name)
                    result = method(filters)

                    self.computed[key] = result
                    return result

        ''')

    def _generate_kpi_engine_class(self) -> str:
        """Generate KPIEngine helper methods."""
        return ""  # Included in header

    def _generate_kpi_stubs(self) -> str:
        """Generate KPI stub functions."""
        code = "\n# ============================================================================\n"
        code += "# KPI Calculation Stubs\n"
        code += "# ============================================================================\n\n"

        # Collect all unique KPIs across datasets
        all_kpis = {}
        for key, dataset in self.datasets.items():
            for kpi in dataset.get("kpis", []):
                if kpi not in all_kpis:
                    all_kpis[kpi] = []
                all_kpis[kpi].append(key)

        for kpi_name in sorted(all_kpis.keys()):
            dataset_keys = all_kpis[kpi_name]
            code += self._generate_kpi_stub(kpi_name, dataset_keys)
            code += "\n"

        return code

    def _generate_kpi_stub(self, kpi_name: str, dataset_keys: list[str]) -> str:
        """Generate stub for single KPI.

        Args:
            kpi_name: KPI identifier
            dataset_keys: List of datasets that consume this KPI

        Returns:
            Python method code
        """
        dataset_list = ", ".join(f'"{k}"' for k in dataset_keys)
        method_name = f"compute_{kpi_name}"

        code = dedent(f'''
            def {method_name}(
                self,
                filters: dict[str, Any] | None = None,
            ) -> KPIResult:
                """Compute KPI: {kpi_name.replace("_", " ").title()}.

                Used by datasets: {dataset_list}

                Args:
                    filters: Filter dictionary (optional)

                Returns:
                    KPIResult with computed value

                TODO: Implement calculation logic:
                    1. Fetch data from MotherDuck or local cache
                    2. Apply filters if provided
                    3. Aggregate/compute metric
                    4. Return KPIResult with value, unit, timestamp
                """
                # TODO: Implement this KPI calculation
                logger.debug("Computing KPI: {kpi_name}")

                return KPIResult(
                    kpi_name="{kpi_name}",
                    dataset_key="unknown",
                    value=0,
                    unit="count",
                    timestamp="TODO",
                    metadata={{"status": "not_implemented"}},
                )

        ''')

        return code
