"""Generate dashboard layout sections from DATASET_REGISTRY.yaml."""

from __future__ import annotations

import logging
from pathlib import Path
from textwrap import dedent
from typing import Any

logger = logging.getLogger(__name__)


class LayoutGenerator:
    """Generates dashboard layout sections from registry."""

    def __init__(self, registry: dict[str, Any]):
        """Initialize layout generator.

        Args:
            registry: Parsed DATASET_REGISTRY.yaml
        """
        self.registry = registry
        self.datasets = registry.get("datasets", {})

    def generate(self) -> str:
        """Generate dashboard layout sections.

        Returns:
            Path to generated file
        """
        output_path = Path(self.registry["generators"]["output_paths"]["layout"])
        output_path.parent.mkdir(parents=True, exist_ok=True)

        code = self._generate_module_header()
        code += self._generate_layout_builder_class()
        code += self._generate_layout_functions()

        with open(output_path, "w") as f:
            f.write(code)

        logger.info(f"Generated layout module: {output_path}")
        return str(output_path)

    def _generate_module_header(self) -> str:
        """Generate module docstring and imports."""
        return dedent('''
            """Auto-generated dashboard layout sections from DATASET_REGISTRY.yaml.

            This module is generated by CodegenFramework.generate_layout().
            DO NOT EDIT MANUALLY — regenerate from registry instead.

            Generated components:
            - LayoutBuilder class for dynamic section assembly
            - Dataset-specific layout functions (e.g., inspection_section, violations_section)

            Usage:
                from app.generated.dash_layouts_sections import LayoutBuilder

                builder = LayoutBuilder()
                layout = builder.build_all_sections()  # Returns Dash layout

                # Or build selectively:
                inspection_layout = builder.build_section("inspection")
            """

            from __future__ import annotations

            import logging
            from typing import Any

            import dash_mantine_components as dmc
            from dash import dcc, html

            logger = logging.getLogger(__name__)


            class LayoutBuilder:
                """Builds dashboard layout sections from registry."""

                def __init__(self):
                    """Initialize layout builder."""
                    pass

                def build_all_sections(self) -> html.Div:
                    """Build all dataset sections.

                    Returns:
                        Dash layout component
                    """
                    sections = [
                        self.build_section("inspection"),
                        self.build_section("violations"),
                        # ... other sections
                    ]
                    return html.Div(sections)

                def build_section(self, dataset_key: str) -> html.Div:
                    """Build layout section for dataset.

                    Args:
                        dataset_key: Dataset identifier

                    Returns:
                        Dash layout component
                    """
                    logger.debug(f"Building section for: {dataset_key}")
                    return html.Div()  # Placeholder

        ''')

    def _generate_layout_builder_class(self) -> str:
        """Generate LayoutBuilder helper methods."""
        return ""  # Included in header

    def _generate_layout_functions(self) -> str:
        """Generate layout functions for datasets."""
        code = "\n# ============================================================================\n"
        code += "# Dataset-Specific Layout Functions\n"
        code += "# ============================================================================\n\n"

        active_datasets = {
            k: v
            for k, v in self.datasets.items()
            if v.get("status") == "active"
        }

        for key, dataset in sorted(active_datasets.items()):
            code += self._generate_dataset_layout(key, dataset)
            code += "\n"

        return code

    def _generate_dataset_layout(self, key: str, dataset: dict[str, Any]) -> str:
        """Generate layout function for single dataset.

        Args:
            key: Dataset key
            dataset: Dataset config

        Returns:
            Python function code
        """
        title = dataset["name"]
        fourfour = dataset["fourfour"]

        code = dedent(f'''
            def create_{key}_section() -> html.Div:
                """Create dashboard section for {title} ({fourfour}).

                Components:
                    - Title card with dataset name and freshness
                    - Chart placeholder (connected to callback)
                    - KPI metrics cards
                    - Narrative insight panel
                    - Data quality scorecard

                Returns:
                    Dash layout component
                """
                return dmc.Paper(
                    withBorder=True,
                    p="lg",
                    radius="lg",
                    shadow="sm",
                    children=[
                        dmc.Title("{title}", order=2),
                        dmc.Text(
                            f"Dataset: {fourfour} | Source: data.cityofnewyork.us",
                            size="sm",
                            c="dimmed",
                            mb="md",
                        ),
                        # Chart container
                        html.Div(
                            [
                                dcc.Graph(
                                    id="chart-{key}",
                                    loading_state={{"is_loading": True}},
                                ),
                                html.Div(id="narrative-{key}"),
                            ]
                        ),
                    ],
                )

        ''')

        return code
