erDiagram
  inspection {
    text inspectionid PK
    text noviolationfound
    text citydoit
    text ownerwilldoit
    text capconflictflag
    text capitalconflicts
    text cancel
    calendar_date inspectiondate
    text is_311_inspection
    text materialid
    text pickupsidewalk
    text curb311
    text pickupcurb
    text other
    text correspondence
    text damageid
    text damagetypecode
  }
  violations {
    text broken
    number cb
    calendar_date certi_date
    text contract
    calendar_date entrydate
    text flag
    text frstname
    number grace_pd
    text hardware
    text house_num
    text integrity
    text onfrtocode
    text onstname
    text other_def
    text patchwork
    calendar_date post_date
    text slope
    number sq_feet
    text sw_missing
    number swv_number
    text tostname
    text trip_haz
    text undermined
    calendar_date vdismissdate
    number violationid PK
    calendar_date vissuedate
    number bblid FK
  }
  reinspection {
    number reinspectionid PK
    text requestreinspection
    calendar_date requestreinspectiondate
    number reinspectsqft
    calendar_date actualreinspectdate
    calendar_date responsedate
    text damageid
    text damagetypecode
  }
  lot_info {
    number bblid
    number block
    number boro
    number lot
    text zipcode
  }
  built {
    number bblid FK
    calendar_date dot_contstruct_date
    text dbo
    calendar_date dbo_date
    text contract
    text atdbystreettree
    text portionofdefectbystreettree
    text noneofdefectbystreettree
    number totalsqftsidewalkrepaired
    number totallfcurbrepaired
    number totalcosttoconstruct
    number totalsqftsdwrepairedstre
    number totallfcurbrepairedstree
    number totalcostofrepairstreett
  }
  dismissals {
    text sr
    calendar_date request_date
    text site_street_address
    number borocode
    number community_board
    number block
    number lot
    number violation
    text permit
    text homeowner_contractor
    number attempt
    calendar_date violation_issue_date
    calendar_date assigned_date
    calendar_date inspection_date
    text pass_fail
    text reason_for_failure
    text car_needed_y_n
    calendar_date date_results_are_mailed
    text expedited
    calendar_date vdd
    text borough
    number postcode
    number latitude
    number longitude
    number council_district
    number bin
    number bbl FK
    number census_tract
    text nta FK
  }
  tree_damage {
    number atdid
    text atd_number
    number bblid FK
    number violationid FK
    number inspectionid FK
    number reinspectionid FK
    calendar_date inspect_date
    calendar_date atdissuedate
    number cb
    text house_num
    text onstname
    text atddismissed
    calendar_date atddismissedon
  }
  correspondences {
    calendar_date date_received
    text borough
    text block
    text lot
    text class
    text community_board
    text violation
    text osm
    text ccu
    text sim
    text bc
    text other_log
    text issue
    text address
    text cross_streets
    text referred_routed_to
    text resoultion
    calendar_date date_closed
    text results_of_inspection
    number postcode
    number latitude
    number longitude
    number council_district
    number census_tract
    number bin
    number bbl FK
    text nta FK
  }
  ramp_progress {
    point the_geom
    number objectid
    number cornerid
    text street_nam
    text street_n_1
    text borough
    text constructi
    text construc_1
    text construc_2
  }
  ramp_complaints {
    number cmt_corner_id
    text street_name1
    text street_name2
    text borough
    number community_district
    number block
    number lot
    text complaint_id PK
    calendar_date complaint_date
    text temp_repair_feasible
    calendar_date temp_repair_date
    text temp_repair_type
    text second_temp_repair_needed
    calendar_date date_second_temp_repair
    text bulkcomplaint
  }
  ramp_locations {
    point the_geom
    number cornerid
    number rampid PK
    text ramp_onstr
    calendar_date geocyclora
    number borough
    text stname1
    text stname2
    number curb_reveal
    number ramp_running_slope_total
    text dws_conditions
    number gutter_slope
    number lnd_width
    number lnd_length
    number lnd_cross_slope
    number counter_slope
    number ramp_width
    number ramp_right_flare
    number ramp_left_flare
    number ramp_length
    number ramp_cross_slope
    text ponding
    text obstacles_ramp
    text obstacles_landing
  }
  curb_metal_protruding {
    text file
    text closed
    text _311
    text sr
    text steel_curb
    text sc_cut
    text ref_to_other
    text cb
    text on_street
    text i_f_o
    text cross_st_1
    text cross_st_2
    text lin_ft
    text sq_ft
    calendar_date rec_d_2
    calendar_date insp
    text borough
  }
  step_streets {
    text boro_cb
    text on_street
    text from
    text to
  }
  street_resurfacing_schedule {
    number workscheduleprojectlocationid
    text boroughname
    text day
    calendar_date date
    text onstreetname
    text fromstreetname
    text tostreetname
    number communityboard
    text area
    text worktype
    text crewtype
    text shifttype
    text oftcode
    number location_segment_id
    text location_wkt
    number location_node_id
  }
  weekly_construction {
    text borough
    text cb
    text contract_no
    text location
  }
  pedestrian_demand {
    multiline the_geom
    text borocode
    text boroname
    text borocd
    text coundist
    text assemdist
    text stsendist
    text congdist
    text street
    text segmentid
    number rank
    number pmp_id
    text nta2020 FK
    text boro
    text category
    text ntaname
    text femafldz
    text femafldt
    text hrcevac
    number shape_leng
  }
  vzv_enhanced_crossings {
    point the_geom
    text date_imple
    text long
    text lat
    text x
    text y
  }
  holiday_construction_embargo_intersection {
    point the_geom
    text oftcode
    text boroughcod
    text primarynam
    text primaryn_1
  }
  vzv_street_improvement_projects_sip_corridor {
    multiline the_geom
    text pjct_name
    text sip_year
    text end_date
    number shape_leng
  }
  bi_annual_pedestrian_counts {
    point the_geom
    text objectid
    text loc
    text borough
    text street_nam
    text from_stree
    text to_street
    text iex
    text may_07_am
    text may_07_pm
    text may_07_md
    text sept_07_am
    text sept_07_pm
    text sept_07_md
    text may_08_am
    text may_08_pm
    text may_08_md
    text sept_08_am
    text sept_08_pm
    text sept_08_md
    text may_09_am
    text may_09_pm
    text may_09_md
    text sept_09_am
    text sept_09_pm
    text sept_09_md
    text may_10_am
    text may_10_pm
    text may_10_md
    text sept_10_am
    text sept_10_pm
    text sept_10_md
    text may_11_am
    text may_11_pm
    text may_11_md
    text sept_11_am
    text sept_11_pm
    text sept_11_md
    text may_12_am
    text may_12_pm
    text may_12_md
    text sept_12_am
    text sept_12_pm
    text sept_12_md
    text may_13_am
    text may_13_pm
    text may_13_md
    text sept_13_am
    text sept_13_pm
    text sept_13_md
    text may_14_am
    text may_14_pm
    text may_14_md
    text sept_14_am
    text sept_14_pm
    text sept_14_md
    text may_15_am
    text may_15_pm
    text may_15_md
    text sept_15_am
    text sept_15_pm
    text sept_15_md
    text may_16_am
    text may_16_pm
    text may_16_md
    text sept_16_am
    text sept_16_pm
    text sept_16_md
    text may_17_am
    text may_17_pm
    text may_17_md
    text sept_17_am
    text sept_17_pm
    text sept_17_md
    text may_18_am
    text may_18_pm
    text may_18_md
    text sept_18_am
    text sept_18_pm
    text sept_18_md
    text may_19_am
    text may_19_pm
    text may_19_md
    text oct_20_am
    text oct_20_pm
    text oct_20_md
    text may_21_am
    text may_21_pm
    text may_21_md
    text oct_21_am
    text oct_21_pm
    text oct_21_md
    text may_22_am
    text may_22_p_m
    text may_22_md
    text oct_22_am
    text oct_22_pm
    text oct_22_md
    text may_23_am
    text may_23_p_m
    text may_23_md
    text oct_23_am
    text oct_23_pm
    text oct_23_md
    text june_24_am
    text june_24_pm
    text june_24_md
    number oct24_am
    number oct24_pm
    text oct24_md
    number may25_am
    number may25_pm
    number may25_md
    number oct25_am
    number oct25_pm
    number oct25_md
  }
  bikes_in_buildings_requests {
    number requestid
    text indexnumber
    text tenantname
    text tenantfloor
    text tenantbuildingnumber
    text tenantstreetname
    text tenantcity
    text tenantstatecode
    number tenantpostcode
    text tenantborough
    text ownername
    text ownerfloor
    text ownerstreetaddress
    text ownercity
    text ownerstatecode
    number ownerzipcode
    text floorsuiterequested
    number noofbicyclerequested
    number bbl FK
    number bin
    calendar_date dateofrequest
    calendar_date requestdateofentry
    calendar_date implementdate
    calendar_date planpostdate
    calendar_date plansubmitdate
    calendar_date exceptionrequestduedate
    calendar_date tenantnotificationexcept
    text locationofentrances
    text routetoelevators
    text regularhoursofoperation
    calendar_date planddatereceived
    text alternateparkinglocation
    text alternateparkingdescription
    text noofbicycleaccomodate
    text routetoalternateparking
    text parkingexceptiondatereceived
    calendar_date parkingexceptiondateofentry
    text dobdevicenumber
    calendar_date dateofbuilding
    calendar_date dateofelevator
    text methodofelevator
    text selfserviceoroperator
    text iscartop
    text iscardoor
    calendar_date elevatorexceptiondatereceived
    text elevatorexceptionhardcop
    calendar_date elevatorexceptiondateofentry
    text requeststatus
    number latitude
    number longitude
    number community_board
    number council_district
    number census_tract
    text nta FK
  }
  vzv_priority_intersections {
    point the_geom
    text street_1
    text street_2
    text long
    text lat
    text x
    text y
  }
  street_pavement_ratings {
    multiline the_geom
    text oftcode
    text boroughname
    text onstreetna
    text fromstreet
    text tostreetna
    number ismultipass
    text direction
    text road_type
    number systemrating
    text nonratingreason
    calendar_date inspection
    number locationgeometry_stlength
  }
  vzv_bike_priority_areas {
    multipolygon the_geom
    text boro_cd_cod
    number shape_leng
    number shape_area
  }
  accessible_pedestrian_signal_locations {
    point the_geom
    text borocode
    text boroname
    text borocd
    text coundist
    text assemdist
    text stsendist
    text congdist
    text location
    text borough
    calendar_date date_insta
    number point_x
    number point_y
    text femafldz
    text femafldt
    text hrcevac
    text ntaname
  }
  parking_permit_for_people_with_disabilities_pppd {
    number permit_tag
    calendar_date effective_date
    calendar_date expiration_date
    text status
    text is_veh_stolen
    calendar_date appl_date
    text status_1
  }
  vzv_leading_pedestrian_interval_signals {
    point the_geom
    text main_street
    text cross_stree
    text install_da
    text long
    text lat
    text x
    text y
  }
  seating_locations {
    point the_geom
    text borocode
    text boroname
    text borocd
    text coundist
    text assemdist
    text stsendist
    text congdist
    text category
    text nearest_add
    text on_street
    text from_street
    text to_street
    text side_of_st
    calendar_date installation_date
    text asset_id
    text asset_subtype
    number latitude
    number longitude
    text siteid
    text ntaname
    text femafldz
    text femafldt
    text hrcevac
  }
  vzv_safe_streets_for_seniors {
    multipolygon the_geom
    text name
    number shape_leng
    number shape_area
  }
  exclusive_pedestrian_signal_barnes_dance_locatio {
    point the_geom
    text borocode
    text boroname
    text borocd
    text coundist
    text assemdist
    text stsendist
    text congdist
    text main_stree
    text cross_stre
    text barnes_dan
    text modified_b
    text mid_block_
    text t_oneway_a
    text t_oneway_1
    calendar_date installati
    text ntaname
    text femafldz
    text femafldt
    text hrcevac
  }
  street_direction_change_requests_2019_present {
    text location
    calendar_date request_date
    text requested_by
    text type_of_request
    text request_status
    text borough
  }
  vzv_street_improvement_projects_sip_intersection {
    multipoint the_geom
    text pjct_name
    number sip_year
    calendar_date end_date
    text long
    text lat
    text x
    text y
  }
  over_dimensional_vehicle_permits_odvp_permit_sti {
    number permitid
    number stipulationid
    text permitnumber
    text stipulationcode
    text stipulationdescription
  }
  street_construction_permits_cranes {
    text permitnumber
    text cranetypeshortdesc
    text craneserialnumber
    calendar_date createdon
    calendar_date modifiedon
  }
  bicycle_parking_shelters {
    point the_geom
    text boro_code
    text boro_name
    text boro_cd
    text coun_dist
    text assem_dist
    text st_sen_dist
    text cong_dist
    text location
    text shelter_id
    text street
    calendar_date build_date
    text ntaname
    text femafldz
    text femafld_t
    text hrc_evac
  }
  protected_streets_intersection_dataset {
    multipoint the_geom
    text oftcode
    text geoborough
    text onstreetna
    text fromstreet
    calendar_date dateprotec
    calendar_date dateprot_1
  }
  highway_travel_permit_annual {
    number permitno
    calendar_date effectivedate
    calendar_date expirationdate
    number companyid
    text companyname
    calendar_date issuedate
    text validdays
    text validtimes
    text fleet_1
    text permitoption
    text validfor
    text buscompany
    text permitpurpose
    text policeescort
    text dotescort
    text otherescort
    text otherescortdesc
    text conditionrestrictions
    text permitrevoked
    text reasonrevoked
    calendar_date daterevoked
  }
  bicycle_and_pedestrian_count_sensors {
    text id
    text name
    number lat
    number lon
    calendar_date firstdata
    calendar_date lastdata
    text granularity
    text travelmodes
    checkbox directional
    checkbox hastimestampeddata
    checkbox hasweather
    text counters_id
    text counters_serial
    calendar_date counters_installationdate
    calendar_date counters_detachmentdate
    text domain_name
  }
  nyc_dot_pedestrian_plazas_point_feature {
    point the_geom
    text borocode
    text boroname
    text borocd
    text coundist
    text assemdist
    text stsendist
    text congdist
    text plazaname
    text boro
    text onstreet
    text fromstreet
    text tostreet
    text partner
    text femafldz
    text femafldt
    text hrcevac
    number point_x
    number point_y
  }
  shared_e_scooter_parking_corrals {
    multipolygon the_geom
    text parking_location
    text type
    text borough
    calendar_date install_da
    number shape_leng
    number shape_area
  }
  pedestrian_space_added {
    text name
    text boro
    number cb
    text on_street
    text cross_street_1
    text cross_street_2
    number area_sf
    number area_acres
    text project_type
  }
  parking_permit_for_people_with_disabilities_pppd_2 {
    text permit_num
    calendar_date effective_date
    calendar_date expiration_date
    calendar_date issue_date
    text permit_status
    text is_veh_stolen
    calendar_date appl_date
    text status
  }
  uptown_bicycle_counts {
    text year
    number hudson_river_greenway_b
    number riverside_drive_a
    number west_end_ave_a
    number broadway_a
    number amsterdam_ave_b
    number columbus_ave_b
    number central_park_west_a
    number central_park_dr_west
    number central_park_dr_east
    number _5th_ave
    number madison_ave
    number park_ave_a
    number lexington_ave
    number _3rd_ave
    number _2nd_ave_b
    number _1st_ave_b
    number york_ave_a
    number east_end_ave_a
    number east_river_greenway_b
    number total
  }
  street_closures_due_to_construction_activities_b {
    multiline the_geom
    number segmentid
    number oft
    text onstreetname
    text fromstreetname
    text tostreetname
    text borough_code
    calendar_date work_start_date
    calendar_date work_end_date
    text uniqueid
    text purpose
  }
  agency_authorized_parking_permits {
    number year
    number arid
    text agencyname
    text agencydesc
    number parkingplacardnumber
    text parkingplacardtype
    text issuingauthority
    text governmentvehicle
    text privatevehicle
    text vehicleplatestate
    text agencytype
    text applicationplacardtype
    text parkingrestriction
    text active
    text activepermit
    number abpermitnumber
    calendar_date abp_issuedate
    calendar_date abp_effectivedate
    calendar_date abp_expirationdate
    number issuereason
    text abpermitrecords_active
    text permittype
    calendar_date deactivatedate
    text returned
    calendar_date returndate
  }
  clergy_parking_permits {
    text houseofworship
    text streetaddress
    text city
    text state
    text postcode
    calendar_date entrydate
    text permitnumber
    calendar_date dateissue
    calendar_date dateexpiry
    text permitstatus
    text permittype
    text borough
    number latitude
    number longitude
    number community_board
    number council_district
    number bin
    number bbl FK
    number census_tract
    text nta FK
  }
  single_use_parking_permit_on_street {
    number permitno
    calendar_date expiration_date
    text companyname
    text city
    text state
    text zipcode
    calendar_date issuedate
    calendar_date permitprintdate
    text permittype
    text location
    text validdates
    text validtimes
    text platestate
    text reason
    text purpose
    text conditionrestrictions
  }
  vzv_street_team_flyers {
    point the_geom
    number total_flyer
    text date
    text long
    text lat
    text x
    text y
  }
  intercity_bus_stop_permits {
    text permitnumber
    text applicationtrackingid
    text sequencenumber
    text applicationtypeshortdesc
    text permitstatusid
    text permitstatusshortdesc
    text permitseriesid
    text permitseriesshortdesc
    text permittypeid
    text permittypedesc
    text specificstipulations
    calendar_date permitissuedate
    calendar_date issuedworkstartdate
    calendar_date issuedworkenddate
    text boroughname
    text onstreetname
    text fromstreetname
    text tostreetname
    text permitteename
    calendar_date createdon
    calendar_date modifiedon
  }
  annual_overweight_load_aol_permits {
    number permitid
    text permitapplication
    text fullpermitno
    text fullapplicationno
    calendar_date applicationdate
    calendar_date issuedate
    calendar_date permitfromdate
    calendar_date permittodate
    text applicationtypename
    text applicationtypeother
    text oldpermitno
    calendar_date oldexpirationdate
    number oldgrossvehicleweight
    text permitservicecompany
    text permitteecompany
    text industrytypename
    text industrytypeother
    text leasecompanyname
    text leaseexpirationdate
    number year
    text make
    text model
    text state
    text cdno
    text serialno
    number manufacturergvwr
    number registeredgvwr
    text vehicletype
    text vehicletypeother
    text permittype
    number overallwidth
    number overalllength
    number overallheight
    number totalnoofaxle
    number wheelbase
    text loadindescription
    number loadinwidth
    number loadinheight
    number loadinlength
    number loadinweight
    text loadoutdescription
    number loadoutwidth
    number loadoutheight
    number loadoutlength
    number loadoutweight
    number steeringweight
    number steeringnooftires
    number steeringloadrating
    number axle2weight
    number axle2space
    number axle2nooftires
    number axle2loadrating
    number axle3weight
    number axle3space
    number axle3nooftires
    number axle3loadrating
    number axle4weight
    number axle4space
    number axle4nooftires
    number axle4loadrating
    number axle5weight
    number axle5space
    number axle5nooftires
    number axle5loadrating
    number axle6weight
    number axle6space
    number axle6nooftires
    number axle6loadrating
    number axle7weight
    number axle7space
    number axle7nooftires
    number axle7loadrating
    number axle8weight
    number axle8space
    number axle8nooftires
    number axle8loadrating
    number axle9weight
    number axle9space
    number axle9nooftires
    number axle9loadrating
    number axle10weight
    number axle10space
    number axle10nooftires
    number axle10loadrating
    number axle11weight
    number axle11space
    number axle11nooftires
    number axle11loadrating
  }
  street_closures_due_to_construction_activities_b_2 {
    text onstreetname
    text fromstreetname
    text tostreetname
    text boroughname
    calendar_date workstartdate
    calendar_date workenddate
    text purpose
    text oftcode
    text wkt
  }
  open_streets_locations {
    number object_id
    text orgname
    text appronstre
    text boroughname
    text apprfromst
    text apprtostre
    text apprdayswe
    text reviewstat
    text apprmonope
    text apprmonclo
    text apprtueope
    text apprtueclo
    text apprwedope
    text apprwedclo
    text apprthuope
    text apprthuclo
    text apprfriope
    text apprfriclo
    text apprsatope
    text apprsatclo
    text apprsunope
    text apprsunclo
    calendar_date apprstartd
    calendar_date apprenddat
    text shape_stle
    text segmentidt
    text segmentidf
    text lionversion
    multiline the_geom
  }
  highway_travel_permit_single_use {
    number permitno
    calendar_date expiration_date
    calendar_date effectivedate
    text companyname
    text companycity
    text companystate
    text companyzip
    calendar_date issuedate
    text validdates
    text validtimes
    text schoolchildren
    text othertransportdesc
    text permitpurpose
    text pelham
    text beltparkway
    text bronxriver
    text crossisland
    text easternparkway
    text grandcentral
    text mosholu
    text hutchinsonriver
    text harlemriver
    text richmondparkway
    text willowbrookparkway
    text henryhudsonparkway
    text jackierobinsonparkway
    text fdr_drive
    text otherparkway
    text otherparkwaydesc
    text conditionrestrictions
  }
  parking_meters_parknyc_block_faces {
    multiline the_geom
    text pay_by_cel
    text vehicle_ty
    text all_vehicl
    text all_vehi_1
    text all_vehi_2
    text all_vehi_3
    text commercial
    text commerci_1
    text commerci_2
    text commerci_3
    text on_street
    text side_of_st
    text from_stree
    text to_street
    text borough
    text meter_rate
    number shape_leng
  }
  dot_in_house_street_resurfacing_projects {
    text oft_code
    text project_type
    text borough_code
    text location_on_street
    text location_from_street
    text location_to_street
    text project_id
    text project_status
    number project_speed_bumps
    number location_community_board
    calendar_date location_actual_milling_start_date
    calendar_date location_actual_milling_end_date
    calendar_date location_actual_paving_start_date
    calendar_date location_actual_paving_end_date
    calendar_date location_actual_protect_until
    number location_actual_lane_miles
    number location_actual_paving_square
    text location_status
    number location_segment_id
    text location_wkt
    text location_node_id
  }
  protected_streets_block_dataset {
    multiline the_geom
    text oftcode
    text geoborough
    text onstreetna
    text fromstreet
    text tostreetna
    calendar_date dateprotec
    calendar_date dateprot_1
    number shape_stle
  }
  bicycle_parking {
    point the_geom
    text borocode
    text boroname
    text borocd
    text coundist
    text assemdist
    text stsendist
    text congdist
    text program
    text site_id
    text group_id
    text borough
    text ifoaddress
    text onstreet
    text fromstreet
    text tostreet
    text side_of_st
    text racktype
    calendar_date date_inst
    number latitude
    number longitude
    text ntaname
    text femafldz
    text femafldt
    text hrcevac
  }
  street_closures_due_to_construction_activities_b_3 {
    point the_geom
    text nodeid
    number oft
    text onstreetname
    text fromstreetname
    text borough_code
    calendar_date work_start_date
    calendar_date work_end_date
    text uniqueid
    text purpose
  }
  annual_on_street_parking_permit_aospp {
    number permit_num
    text vas_org
    text prim_territory
    number dot_id
    number veh_hrs_from
    text veh_hrs_from_ampm
    number veh_hrs_to
    text veh_hrs_to_ampm
    text sun
    text mon
    text tue
    text wed
    text thur
    text fri
    text sat
    calendar_date effective_date
    calendar_date expiration_date
    calendar_date issue_date
    text permit_status
    text plate_state
    text is_veh_stolen
    calendar_date appl_date
    text status
    text appl_definition
    text city
    text state
    number zip
  }
  bus_lanes_local_streets {
    multiline the_geom
    text street
    text bltrafdir
    text segmentid
    text rw_type
    number streetwidt
    text boro
    text facility
    text direction
    text hours
    text days
    number days_code
    text lane_width
    text lane_type1
    text lane_type
    text lane_type2
    text lane_color
    text sbs_route1
    text sbs_route2
    text sbs_route3
    text open_dates
    number year1
    number year2
    number year3
    text last_updat
    text chron_id_1
    number shape_leng
    multiline shape_le_1
    text mid_block
  }
  street_pothole_work_orders_closed_dataset {
    multiline the_geom
    text defnum
    text initby
    text housenum
    text oft
    text onfacename
    text onprimname
    text frmprimnam
    text toprimname
    text specloc
    text boro
    text source
    calendar_date rptdate
    calendar_date rptclosed
    number shape_leng
  }
  new_york_city_bike_routes {
    multiline the_geom
    number segmentid
    number bikeid
    text prevbikeid
    text status
    number boro
    text street
    text fromstreet
    text tostreet
    text onoffst
    text facilitycl
    text allclasses
    text bikedir
    number lanecount
    text ft_facilit
    text tf_facilit
    text ft2facilit
    text tf2facilit
    calendar_date instdate
    calendar_date ret_date
    text grnwy
    text gwsystem
    text gwsys2
    text spur
    text gwyjuris
  }
  carshare_locations_curbside {
    point the_geom
    text carshare_c
    text site_reque
    text on_street
    text from_
    text to
    text address
    text site_id
    number community
    text side
    text borough
    number lat
    number long
    point geom2
  }
  over_dimensional_vehicle_permits_odvp {
    number permitid
    text fullpermitno
    text fullapplicationno
    date applicationdate
    date issuedate
    date permitdate
    date permitdateto
    date permitallowedfrom
    date permitallowedto
    text permitservicecompany
    text permitteecompany
    text truckyear
    text truckmake
    text truckstate
    text trailerlicno
    text traileryear
    text trailermake
    text trailerstate
    number overallwidth
    number overalllength
    number overallheight
    number trailerlength
    number totalgrossweight
    text descriptionofload
    number loadheight
    number loadwidth
    number loadlength
    number loadweight
    text startstreetaddress
    text startcity
    text startstate
    text startzipcode
    text startcountyline
    text endstreetaddress
    text endcity
    text endstate
    text endzipcode
    text endcountyline
    number totalnumberofaxle
    number steeringweight
    number axle2weight
    number axle2space
    number axle3weight
    number axle3space
    number axle4weight
    number axle4space
    number axle5weight
    number axle5space
    number axle6weight
    number axle6space
    number axle7weight
    number axle7space
    number axle8weight
    number axle8space
    number axle9weight
    number axle9space
    number axle10weight
    number axle10space
    number axle11weight
    number axle11space
    number wheelbase
  }
  street_travel_permit {
    number companyid
    text companyname
    text validdates
    number permitno
    calendar_date expirationdate
    calendar_date issuedate
    calendar_date permitprintdate
    text validtimes
    calendar_date effectivedate
    text permitpurpose
    number permitqty
    number qtyreturn
    text conditionrestrictions
    text return
    calendar_date returndate
  }
  street_and_highway_capital_reconstruction_projec {
    multipoint the_geom
    number projectid
    text projtitle
    text fmsid
    number fmsagencyi
    text leadagency
    number managingag
    text projectdes
    text projecttyp
    text projectt_1
    text projectsta
    number constructi
    calendar_date designstar
    calendar_date construc_2
    number currentfun
    number projectcos
    text overallsco
    text safetyscop
    text otherscope
    text projectjus
    text onstreetna
    text fromstreet
    text tostreetna
    text boroughnam
    text oftcode
    number designfy
    number latitude
    number longitude
    text x
    text y
  }
  temporary_parking_permit_for_people_with_disabil {
    number permitno
    calendar_date permitexpiredate
    calendar_date effectivedate
    text permittype
    text location
    text validtimes
    text stateplate
  }
  street_seats_2021_2024 {
    number year
    number borocode
    number borocd
    number assemdist
    number stsendist
    number congdist
    text location
    text address
    text borough
    text postcode
    text on_street
    text to_street
    text from_street
    text type
    text partner
    text status
    number xcoordin
    number ycoordin
    text femafldz
    text femafldt
    number hrcevac
    number latitude
    number longitude
    number community_board
    number council_district
    number census_tract
    number bin
    number bbl FK
    text nta FK
  }
  holiday_construction_embargo_block {
    multiline the_geom
    text oftcode
    text boroughcod
    text onstreetna
    text fromstreet
    text tostreetna
  }
  street_and_highway_capital_reconstruction_projec_2 {
    multiline the_geom
    number projectid
    text projtitle
    text fmsid
    number fmsagencyi
    text leadagency
    number managingag
    text projectdes
    text projecttyp
    text projectt_1
    text projectsta
    number constructi
    calendar_date designstar
    calendar_date construc_2
    number currentfun
    number projectcos
    text overallsco
    text otherscope
    text projectjus
    text onstreetna
    text fromstreet
    text tostreetna
    text boroughnam
    text oftcode
    number location_1
    number designfy
    text safetyscop
  }
  annual_overweight_load_aol_permits_stipulations {
    number permitid
    number stipulationid
    text permitnumber
    text stipulationcode
    text stipulationdescription
  }
  street_network_changes {
    text on_street
    text from_st
    text to_street
    calendar_date completion_date
    text type_of_change
    text new_direction
    text boro
    text notes
  }
  agency_business_parking_permit_abpp {
    text customer_status
    number permit_num
    calendar_date effective_date
    calendar_date expiration_date
    text plate_state
    text plate_type
    text driver_fm_ind
    text restrict_loc
    text sec_plate_state
    text is_veh_stolen
    text stkr_state
    calendar_date appl_date
    text status_1
    text app_definition
    text city
    text state
    text zip
    text boro
  }
  newsrack_inspections {
    number newsracklocationid
    text boroughname
    text publishername
    text publicationname
    text newsrackstatus
    text newsrackstatustype
    calendar_date newsrackstatusdate
    text newsrackactive
    text onstreetname
    text fromstreetname
    text tostreetname
    text compassdirection
    text specificlocation
    number communitydistrictleft
    calendar_date lastinspecteddate
    text lastinspectionresult
  }
  nyc_dot_pedestrian_plazas_polygon {
    multipolygon the_geom
    number objectid
    text borocd
    text assemdist
    text coundist
    text congdist
    text stsendist
    text plazaname
    text onstreet
    text fromstreet
    text tostreet
    text partner
    text borocode
    text boroname
    text femafldz
    text femafldt
    text hrcevac
    number shape_leng
    number shape_area
  }
  e_9_11_authorized_bus_parking_permit {
    number permityear
    number permitno
    text reservationnumber
    calendar_date valid_date
    text busarrivaltime
    text permitnumber
    text companyname
    text dayofweek
    number numberofbuses
    text city
    text state
    text zipcode
    calendar_date issuedate
    text permittype
    text vehicletype
    text buscompanyname
    number permitqty
    number qtyreturn
    text return
    calendar_date returndate
    text conditionrestrictions
    text placereciepthere
  }
  encroachments_and_defacements {
    text complaintid
    text srnumber
    text complainttype
    text boro
    text block
    text lot
    text number
    text street
    text city
    text state
    text postcode
    text unit
    calendar_date initialinspectiondate
    text initialinspectionresults
    calendar_date ordermailingdate
    text postinginspectiondate
    calendar_date followupinspectiondate
    text daysbetween
    calendar_date closeddate
    calendar_date reinspectiondate
    text reinspectionresult
    text novnumber
    text novcode
    calendar_date novdate
    text novdescription
  }
  complaints_311 {
    text unique_key
    calendar_date created_date
    calendar_date closed_date
    text agency
    text agency_name
    text complaint_type
    text descriptor
    text descriptor_2
    text location_type
    text incident_zip
    text incident_address
    text street_name
    text cross_street_1
    text cross_street_2
    text intersection_street_1
    text intersection_street_2
    text address_type
    text city
    text landmark
    text facility_type
    text status
    calendar_date due_date
    text resolution_description
    calendar_date resolution_action_updated_date
    text community_board
    text council_district
    text police_precinct
    text bbl FK
    text borough
    number x_coordinate_state_plane
    number y_coordinate_state_plane
    text open_data_channel_type
    text park_facility_name
    text park_borough
    text vehicle_type
    text taxi_company_borough
    text taxi_pick_up_location
    text bridge_highway_name
    text bridge_highway_direction
    text road_ramp
    text bridge_highway_segment
    number latitude
    number longitude
    point location
  }
  street_centerline {
    multiline the_geom
    number physicalid
    text l_low_hn
    text l_high_hn
    text r_low_hn
    text r_high_hn
    text l_zip
    text r_zip
    text status
    text bike_lane
    text trafdir
    number rw_type
    text pre_type
    text post_type
    number objectid
    text fcc
    number l_blockfaceid
    number r_blockfaceid
    number avgtravtime
    text rwjurisdiction
    text nominaldir
    text accessible
    text nonped
    text boroughcode
    text borough_indicator
    text seglocstatus
    text sandist_ind
    text lsubsect
    text rsubsect
    text continuous_parity_flag
    text twisted_parity_flag
    number posted_speed
    number segmentlength
    number streetwidth
    text streetwidth_irr
    text special_disaster
    text fire_lane
    date created_date
    date modified_date
    text within_bndy_dist
    text truck_route_type
    text collectionmethod
    number from_level_code
    number to_level_code
    text b5sc
    text snow_priority
    text joinid
    number bphys_id
    text carto_display_level
    number number_travel_lanes
    number number_park_lanes
    number number_total_lanes
    text pre_modifier
    text pre_directional
    text post_directional
    text post_modifier
    text full_street_name
    text bike_trafdir
    number shape_length
    text globalid
    text segment_type
    text segment_type_value
    text street_name
    text stname_label
  }
  nta_2020 {
    number borocode
    text boroname
    text countyfips
    text nta2020
    text ntaname
    text ntaabbrev
    text ntatype
    text cdta2020
    text cdtaname
    number shape_leng
    number shape_area
    multipolygon the_geom
  }
  census_demographics_nta {
    text geographic_area_borough
    number geographic_area_2010_census_fips_county_code
    text geographic_area_neighborhood_tabulation_area_nta_code PK
    text geographic_area_neighborhood_tabulation_area_nta_name
    number total_population_2000_number
    number total_population_2010_number
    number total_population_change_2000_2010_number
    number total_population_change_2000_2010_percent
  }
  heat_vulnerability_index {
    text zcta20 PK
    number hvi
  }
  motor_vehicle_collisions_crashes {
    calendar_date crash_date
    text crash_time
    text borough
    text zip_code
    number latitude
    number longitude
    location location
    text on_street_name
    text off_street_name
    text cross_street_name
    number number_of_persons_injured
    number number_of_persons_killed
    number number_of_pedestrians_injured
    number number_of_pedestrians_killed
    number number_of_cyclist_injured
    number number_of_cyclist_killed
    number number_of_motorist_injured
    number number_of_motorist_killed
    text contributing_factor_vehicle_1
    text contributing_factor_vehicle_2
    text contributing_factor_vehicle_3
    text contributing_factor_vehicle_4
    text contributing_factor_vehicle_5
    number collision_id PK
    text vehicle_type_code1
    text vehicle_type_code2
    text vehicle_type_code_3
    text vehicle_type_code_4
    text vehicle_type_code_5
  }
  motor_vehicle_collisions_person {
    number unique_id PK
    number collision_id FK
    calendar_date crash_date
    text crash_time
    text person_id
    text person_type
    text person_injury
    text vehicle_id
    number person_age
    text ejection
    text emotional_status
    text bodily_injury
    text position_in_vehicle
    text safety_equipment
    text ped_location
    text ped_action
    text complaint
    text ped_role
    text contributing_factor_1
    text contributing_factor_2
    text person_sex
  }
  sidewalk_cafes {
    multiline the_geom
    text cafe_type
    number shape_leng
  }
  street_tree_census_2015 {
    number tree_id PK
    number block_id
    calendar_date created_at
    number tree_dbh
    number stump_diam
    text curb_loc
    text status
    text health
    text spc_latin
    text spc_common
    text steward
    text guards
    text sidewalk
    text user_type
    text problems
    text root_stone
    text root_grate
    text root_other
    text trunk_wire
    text trnk_light
    text trnk_other
    text brch_light
    text brch_shoe
    text brch_other
    text address
    number zipcode
    text zip_city
    number cb_num
    number borocode
    text boroname
    number cncldist
    number st_assem
    number st_senate
    text nta FK
    text nta_name
    number boro_ct
    text state
    number latitude
    number longitude
    number x_sp
    number y_sp
    number council_district
    number census_tract
    number bin
    number bbl FK
  }
  forestry_inspections {
    number objectid PK
    text inspectiontype
    text inspectionstatus
    text inspectiontpcondition
    text inspectiontpstructure
    text treepointdbh
    text swtreeconditionrating
    text swlocationrating
    text swclearancerating
    text swdamagerating
    text swdamagedflagstonesrating
    text swratingtotal
    text treepointglobalid
    text plantingspaceglobalid
    text servicerequestglobalid
    text geometry
    text globalid
    calendar_date inspectiondate
    calendar_date closeddate
    calendar_date createddate
    calendar_date updateddate
    text parentinspectionglobalid
    calendar_date reinspectiondate
    text swtotaltrees
    point location
  }
  water_sewer_permits {
    text propertyborough
    text propertyblock
    text propertylot
    text propertyzip
    text permitnumber PK
    calendar_date issuancedate
    text applicationtype
    text requeststatus
  }
  street_construction_permits {
    text permitnumber PK
    text applicationtrackingid
    text sequencenumber
    text applicationtypeshortdesc
    text permitstatusid
    text permitstatusshortdesc
    text permitseriesid
    text permitseriesshortdesc
    text permittypeid
    text permittypedesc
    number permitnumberofzones
    number permitlinearfeet
    number permittotalsqfeet
    number permitestimatednumberofcuts
    text equipmenttypedesc
    number numberofcontainers
    number numberofminicontainers
    text specificstipulations
    text previouspermitnumber
    text nextpermitnumber
    calendar_date emergencyissuedate
    calendar_date permitissuedate
    calendar_date issuedworkstartdate
    calendar_date issuedworkenddate
    text boroughname
    text permithousenumber
    text onstreetname
    text fromstreetname
    text tostreetname
    text permitteename
    text permitpurposecomments
    text permitlocationcomments
    text pavementshortdesc
    text sidewalkshortdesc
    calendar_date createdon
    calendar_date modifiedon
    text oftcode
    text wkt
    text locationgeometry
  }
  dob_stalled_construction_sites {
    text borough_name
    text community_board
    text bin
    text house_number
    text street_name
    text complaint_number PK
    calendar_date date_complaint_received
    calendar_date dobrundate
  }
  lot_info ||--o{ violations : "bblid"
  lot_info ||--o{ built : "bblid"
  nta_2020 ||--o{ dismissals : "nta"
  lot_info ||--o{ dismissals : "bbl"
  inspection ||--o{ tree_damage : "inspectionid"
  violations ||--o{ tree_damage : "violationid"
  reinspection ||--o{ tree_damage : "reinspectionid"
  lot_info ||--o{ tree_damage : "bblid"
  nta_2020 ||--o{ correspondences : "nta"
  lot_info ||--o{ correspondences : "bbl"
  nta_2020 ||--o{ pedestrian_demand : "nta2020"
  nta_2020 ||--o{ bikes_in_buildings_requests : "nta"
  lot_info ||--o{ bikes_in_buildings_requests : "bbl"
  nta_2020 ||--o{ clergy_parking_permits : "nta"
  lot_info ||--o{ clergy_parking_permits : "bbl"
  nta_2020 ||--o{ street_seats_2021_2024 : "nta"
  lot_info ||--o{ street_seats_2021_2024 : "bbl"
  lot_info ||--o{ complaints_311 : "bbl"
  nta_2020 ||--o{ census_demographics_nta : "geographic_area_neighborhood_tabulation_area_nta_code"
  motor_vehicle_collisions_crashes ||--o{ motor_vehicle_collisions_person : "collision_id"
  nta_2020 ||--o{ street_tree_census_2015 : "nta"
  lot_info ||--o{ street_tree_census_2015 : "bbl"