global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'NYC Data Toolkit'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:16686']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
