[server]
headless = true
port = 8501
address = "0.0.0.0"
maxUploadSize = 200

[theme]
primaryColor = "#003366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#212529"
font = "sans serif"

[browser]
gatherUsageStats = false
