import json
from datetime import datetime
from pathlib import Path

import dash
import dash_mantine_components as dmc
from dash import Input, Output, State, dcc, no_update

from app.services.universal_exporter import UniversalExporter

exporter = UniversalExporter()

def register_export_callbacks(app, dm_instance):
    @app.callback(
        Output("notifications-container", "children", allow_duplicate=True),
        Input("btn-jupyter-export", "n_clicks"),
        State("store-data-loaded", "data"),
        prevent_initial_call=True
    )
    def export_jupyter_notebook(n_clicks, data_loaded):
        if not data_loaded: return no_update
        output_path = Path("exports/analyst_export.ipynb")
        output_path.parent.mkdir(exist_ok=True)
        with open(output_path, "w") as f:
            json.dump({"cells": [], "metadata": {}, "nbformat": 4, "nbformat_minor": 5}, f)
        return dmc.Notification(title="Jupyter Export Complete", message=f"Generated at {output_path.absolute()}", color="indigo", action="show")

    @app.callback(
        Output("audit-log-terminal", "children"),
        [Input("url", "pathname"), Input("global-boro-filter", "value")],
        State("audit-log-terminal", "children")
    )
    def update_audit_log(path, boro, current_log):
        if current_log is None: current_log = []
        ts = datetime.now().strftime("%H:%M:%S")
        entry = f"[{ts}] ACCESS: {path} | FILTER: {boro}"
        current_log.insert(0, dmc.Text(entry, size="xs", ff="monospace", c="gray"))
        return current_log[:50]

    @app.callback(
        [Output("download-manager", "data"),
         Output("notifications-container", "children", allow_duplicate=True)],
        Input({"type": "btn-export", "index": dash.ALL}, "n_clicks"),
        State("store-global-filters", "data"),
        prevent_initial_call=True
    )
    def handle_asset_export(n_clicks, filters):
        ctx = dash.callback_context
        if not ctx.triggered or not any(n_clicks): return no_update, no_update
        triggered_id = json.loads(ctx.triggered[0]["prop_id"].split(".")[0])
        export_type, chart_id = triggered_id["index"].split("-", 1)

        target_ds = "inspection"
        if "built" in chart_id or "velocity" in chart_id: target_ds = "built"
        elif "violation" in chart_id: target_ds = "violations"
        elif "lot" in chart_id or "mappluto" in chart_id: target_ds = "lot_info"

        from app.services.dashboard_state import DashboardStateAdapter
        state = DashboardStateAdapter(dm_instance, filters)
        df = state.get_dataset_by_key(target_ds)

        if df is None or df.empty:
            return no_update, dmc.Notification(title="Export Alert", message="No data available to export.", color="orange", action="show")

        title = f"Export: {chart_id}"
        stats = {"Rows": len(df), "Columns": len(df.columns), "Generated": datetime.now().isoformat(timespec="seconds")}

        if export_type == "csv":
            csv_str = exporter.export_data_to_csv(df, title, stats)
            if csv_str:
                return dcc.send_string(csv_str, f"{chart_id}_export.csv"), no_update
        elif export_type == "md":
            content = f"# Export: {chart_id}\n\n## Data Preview\n\n" + df.head(10).to_markdown()
            return dcc.send_string(content, f"{chart_id}_report.md"), no_update
        elif export_type == "py":
            content = f"import pandas as pd\n# Autogenerated Snippet for {chart_id}\ndf = pd.read_csv('{chart_id}_export.csv')\nprint(df.describe())"
            return dcc.send_string(content, f"{chart_id}_script.py"), no_update
        elif export_type in ("xlsx", "excel"):
            xb = exporter.export_data_to_excel(df, title, None, stats)
            if xb:
                return dcc.send_bytes(xb, f"{chart_id}_export.xlsx"), no_update
        elif export_type == "pdf":
            pb = exporter.export_figure_to_pdf(None, title, stats, table_df=df)
            if pb:
                return dcc.send_bytes(pb, f"{chart_id}_export.pdf"), no_update
        elif export_type == "pptx":
            pb = exporter.export_data_to_pptx(df, title, stats)
            if pb:
                return dcc.send_bytes(pb, f"{chart_id}_export.pptx"), no_update

        msg = f"Export type '{export_type.upper()}' is not supported."
        return no_update, dmc.Notification(title="Export Alert", message=msg, color="orange", action="show")

    @app.callback(
        [Output("download-manager", "data", allow_duplicate=True),
         Output("notifications-container", "children", allow_duplicate=True)],
        Input("btn-global-export-pdf", "n_clicks"),
        Input("btn-global-export-excel", "n_clicks"),
        Input("btn-global-export-pptx", "n_clicks"),
        State("store-global-filters", "data"),
        prevent_initial_call=True
    )
    def handle_global_export(pdf_clicks, excel_clicks, pptx_clicks, filters):
        ctx = dash.callback_context
        if not ctx.triggered:
            return no_update, no_update

        triggered_id = ctx.triggered[0]["prop_id"].split(".")[0]

        from app.services.dashboard_state import DashboardStateAdapter
        state = DashboardStateAdapter(dm_instance, filters)
        # Cap interactive view exports; ingestion is uncapped (No-Data-Limits mandate governs ingest only).
        # Pass the cap so get_combined_dataset reads at most cap/n_datasets rows per table (fast path).
        _EXPORT_ROW_CAP = 50_000
        combined_df = state.get_combined_dataset(export_cap=_EXPORT_ROW_CAP)
        _cap_note = ""
        if len(combined_df) > _EXPORT_ROW_CAP:
            _cap_note = f" (first {_EXPORT_ROW_CAP:,} of {len(combined_df):,} rows)"
            combined_df = combined_df.head(_EXPORT_ROW_CAP)
        if combined_df.empty:
            return no_update, dmc.Notification(
                title="Export Error",
                message="No data available for the selected datasets and filters.",
                color="red",
                action="show"
            )

        ts = datetime.now().strftime("%Y%m%d_%H%M%S")

        if triggered_id == "btn-global-export-excel":
            excel_bytes = exporter.export_data_to_excel(combined_df, "NYC DOT Complete Export")
            if excel_bytes:
                return dcc.send_bytes(excel_bytes, f"NYC_DOT_Complete_Export_{ts}.xlsx"), dmc.Notification(
                    title="Export Complete", message=f"Global Excel export generated successfully{_cap_note}.", color="green", action="show"
                )
            return no_update, dmc.Notification(title="Export Error", message="Failed to generate Excel.", color="red", action="show")

        elif triggered_id == "btn-global-export-pdf":
            # Per-dataset summary chart over the current filtered selection.
            import plotly.graph_objects as go
            if "_source_dataset" in combined_df.columns:
                vc = combined_df["_source_dataset"].value_counts()
                fig = go.Figure(go.Bar(x=list(vc.index), y=list(vc.values),
                                       marker_color="#2563EB"))
                fig.update_layout(title="Records by Dataset (filtered)",
                                  template="plotly_white", height=420)
            else:
                fig = go.Figure(go.Indicator(mode="number", value=len(combined_df),
                                             title={"text": "Total Exported Records"}))
            stats = {
                "Total Rows": len(combined_df),
                "Columns": len(combined_df.columns),
                "Datasets": combined_df["_source_dataset"].nunique() if "_source_dataset" in combined_df.columns else 1,
                "Filters": ", ".join(filters.get("boroughs", [])) if filters else "ALL",
                "Generated At": ts,
            }
            pdf_bytes = exporter.export_figure_to_pdf(
                fig, "NYC DOT Executive Telemetrics", stats, table_df=combined_df)

            if pdf_bytes:
                return dcc.send_bytes(pdf_bytes, f"NYC_DOT_Complete_Export_{ts}.pdf"), dmc.Notification(
                    title="Export Complete", message=f"Global PDF export generated successfully{_cap_note}.", color="green", action="show"
                )
            return no_update, dmc.Notification(title="Export Error", message="Failed to generate PDF.", color="red", action="show")

        elif triggered_id == "btn-global-export-pptx":
            import plotly.graph_objects as go
            fig = None
            if "_source_dataset" in combined_df.columns:
                vc = combined_df["_source_dataset"].value_counts()
                fig = go.Figure(go.Bar(x=list(vc.index), y=list(vc.values),
                                       marker_color="#2563EB"))
                fig.update_layout(title="Records by Dataset (filtered)",
                                  template="plotly_white")
            stats = {
                "Total Rows": len(combined_df),
                "Columns": len(combined_df.columns),
                "Generated At": ts,
            }
            pptx_bytes = exporter.export_data_to_pptx(
                combined_df, "NYC DOT Complete Export", stats, figure=fig)
            if pptx_bytes:
                return dcc.send_bytes(pptx_bytes, f"NYC_DOT_Complete_Export_{ts}.pptx"), dmc.Notification(
                    title="Export Complete", message=f"Global PPTX export generated successfully{_cap_note}.", color="green", action="show"
                )
            return no_update, dmc.Notification(title="Export Error", message="Failed to generate PPTX.", color="red", action="show")

    @app.callback(
        Output("notifications-container", "children", allow_duplicate=True),
        Input({"type": "btn-copy", "index": dash.ALL}, "n_clicks"),
        prevent_initial_call=True
    )
    def handle_clipboard_copy(n_clicks):
        if not any(n_clicks): return no_update
        return dmc.Notification(title="System Alert", message="Asset URI copied to secure clipboard.", color="dark", action="show")
