"""Interactive setup wizard for NYC DOT Sidewalk Toolkit local deployment."""

from __future__ import annotations

import os
import platform
import subprocess
import sys
from pathlib import Path
from typing import Any

import click
import yaml

DEFAULT_DOMAIN = "data.cityofnewyork.us"
ENV_KEYS = (
    "SOCRATA_APP_TOKEN",
    "SOCRATA_DOMAIN",
    "PG_DSN",
    "DATA_DIR",
    "OUTPUT_DIR",
    "ANALYST_PROFILE",
    "DUCKDB_PATH",
)

def detect_os() -> str:
    """Return a short OS label (windows, linux, darwin, other)."""
    name = sys.platform
    if name.startswith("win"):
        return "windows"
    if name == "darwin":
        return "darwin"
    if name.startswith("linux"):
        return "linux"
    return "other"

def project_root(start: Path | None = None) -> Path:
    """Resolve repository root (directory containing pyproject.toml)."""
    cur = (start or Path.cwd()).resolve()
    for candidate in [cur, *cur.parents]:
        if (candidate / "pyproject.toml").exists():
            return candidate
    return cur

def _example_profile_path(root: Path) -> Path:
    return root / "config" / "analyst_profile.example.yaml"

def _default_answers(root: Path) -> dict[str, str]:
    prof = os.getenv("TOOLKIT_PROFILE", "") or "default"
    prof_dir = root / "config" / "profiles" / prof
    return {
        "SOCRATA_APP_TOKEN": os.getenv("SOCRATA_APP_TOKEN", ""),
        "SOCRATA_DOMAIN": os.getenv("SOCRATA_DOMAIN", DEFAULT_DOMAIN),
        "PG_DSN": os.getenv("PG_DSN", ""),
        "DATA_DIR": os.getenv("DATA_DIR", str(root / "data")),
        "OUTPUT_DIR": os.getenv("OUTPUT_DIR", str(root / "outputs")),
        # Multi-profile default: config/profiles/<name>/analyst_profile.yaml (still allows legacy config/analyst_profile.yaml)
        "ANALYST_PROFILE": os.getenv("ANALYST_PROFILE", str(prof_dir / "analyst_profile.yaml")),
        "DUCKDB_PATH": os.getenv("DUCKDB_PATH", str(root / "data" / "local_db" / "nyc_mission_control.duckdb")),
    }

def _prompt_values(root: Path, defaults: dict[str, str]) -> dict[str, str]:
    click.echo(f"\nDetected OS: {detect_os()} ({platform.system()} {platform.release()})")
    click.echo(f"Project root: {root}\n")

    profile_name = click.prompt(
        "Profile name (creates config/profiles/<name>/...)",
        default=os.getenv("TOOLKIT_PROFILE", "default"),
        show_default=True,
    )
    token = click.prompt(
        "Socrata app token (SOCRATA_APP_TOKEN, Enter to skip)",
        default=defaults["SOCRATA_APP_TOKEN"],
        hide_input=bool(defaults["SOCRATA_APP_TOKEN"]),
        show_default=False,
    )
    domain = click.prompt("Socrata domain", default=defaults["SOCRATA_DOMAIN"])
    pg_dsn = click.prompt(
        "PostgreSQL DSN (PG_DSN, optional — Enter to skip)",
        default=defaults["PG_DSN"] or "",
        show_default=bool(defaults["PG_DSN"]),
    )
    data_dir = click.prompt("Data directory", default=defaults["DATA_DIR"], type=click.Path())
    output_dir = click.prompt("Output directory", default=defaults["OUTPUT_DIR"], type=click.Path())
    # Default to the multi-profile layout; allow override.
    prof_dir = root / "config" / "profiles" / str(profile_name).strip()
    prof_dir.mkdir(parents=True, exist_ok=True)
    profile_default = str(prof_dir / "analyst_profile.yaml")
    profile = click.prompt("Analyst profile YAML path", default=profile_default, type=click.Path())
    duckdb = click.prompt("DuckDB database path", default=defaults["DUCKDB_PATH"], type=click.Path())

    return {
        "TOOLKIT_PROFILE": str(profile_name).strip(),
        "SOCRATA_APP_TOKEN": token.strip(),
        "SOCRATA_DOMAIN": domain.strip(),
        "PG_DSN": pg_dsn.strip(),
        "DATA_DIR": str(Path(data_dir).resolve()),
        "OUTPUT_DIR": str(Path(output_dir).resolve()),
        "ANALYST_PROFILE": str(Path(profile).resolve()),
        "DUCKDB_PATH": str(Path(duckdb).resolve()),
    }

def _answers_from_env(root: Path) -> dict[str, str]:
    """Non-interactive mode: read wizard inputs from environment."""
    defaults = _default_answers(root)
    out = {}
    for key in ENV_KEYS:
        val = os.getenv(key, defaults[key])
        out[key] = val.strip() if isinstance(val, str) else str(val)
    out["TOOLKIT_PROFILE"] = os.getenv("TOOLKIT_PROFILE", "default").strip() or "default"
    if not out.get("SOCRATA_APP_TOKEN") and os.getenv("WIZARD_ALLOW_EMPTY_TOKEN") != "1":
        click.echo(
            "Set SOCRATA_APP_TOKEN or WIZARD_ALLOW_EMPTY_TOKEN=1 for non-interactive setup.",
            err=True,
        )
        raise click.Abort()
    return out

def write_env_file(root: Path, values: dict[str, str], env_path: Path | None = None) -> Path:
    """Write .env in project root with toolkit variables."""
    dest = env_path or (root / ".env")
    lines = [
        "# Generated by socrata_toolkit.install_wizard",
        f"TOOLKIT_PROFILE={values.get('TOOLKIT_PROFILE','default')}",
        f"SOCRATA_DOMAIN={values['SOCRATA_DOMAIN']}",
        f"SOCRATA_APP_TOKEN={values['SOCRATA_APP_TOKEN']}",
        f"PG_DSN={values['PG_DSN']}",
        f"DATA_DIR={values['DATA_DIR']}",
        f"OUTPUT_DIR={values['OUTPUT_DIR']}",
        f"ANALYST_PROFILE={values['ANALYST_PROFILE']}",
        f"DUCKDB_PATH={values['DUCKDB_PATH']}",
        "",
        "# Docker analyst stack (optional)",
        f"POSTGRES_USER={os.getenv('POSTGRES_USER', 'dot_user')}",
        f"POSTGRES_PASSWORD={os.getenv('POSTGRES_PASSWORD', 'dot_pass')}",
        f"POSTGRES_DB={os.getenv('POSTGRES_DB', 'sidewalk_db')}",
    ]
    dest.write_text("\n".join(lines), encoding="utf-8")
    return dest

def ensure_directories(values: dict[str, str]) -> None:
    for key in ("DATA_DIR", "OUTPUT_DIR"):
        Path(values[key]).mkdir(parents=True, exist_ok=True)
    pack = Path(values["OUTPUT_DIR"]) / "analyst_pack"
    pack.mkdir(parents=True, exist_ok=True)

def write_analyst_profile(
    root: Path,
    values: dict[str, str],
    *,
    force: bool = False,
) -> Path | None:
    """Copy example analyst profile and patch paths."""
    dest = Path(values["ANALYST_PROFILE"])
    example = _example_profile_path(root)
    if dest.exists() and not force:
        click.echo(f"Analyst profile already exists: {dest}")
        return dest
    if not example.exists():
        click.echo(f"Warning: example profile missing at {example}", err=True)
        return None

    data = yaml.safe_load(example.read_text(encoding="utf-8")) or {}
    # Keep profile_name aligned with folder for stable multi-profile behavior.
    if values.get("TOOLKIT_PROFILE"):
        data["profile_name"] = str(values["TOOLKIT_PROFILE"])
    data["duckdb_path"] = values["DUCKDB_PATH"]
    outputs = data.get("outputs") or {}
    if isinstance(outputs, dict):
        outputs["dir"] = str(Path(values["OUTPUT_DIR"]) / "analyst_pack")
        data["outputs"] = outputs

    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(yaml.dump(data, default_flow_style=False, sort_keys=False), encoding="utf-8")
    return dest

def test_socrata(token: str, domain: str) -> tuple[bool, str]:
    if not token:
        return False, "No SOCRATA_APP_TOKEN provided"
    try:
        import requests

        url = "https://api.us.socrata.com/api/catalog/v1"
        resp = requests.get(
            url,
            params={"domains": domain, "limit": 1},
            headers={"X-App-Token": token},
            timeout=15,
        )
        if resp.status_code == 200:
            return True, "Socrata catalog reachable"
        return False, f"Socrata returned HTTP {resp.status_code}"
    except Exception as exc:
        return False, str(exc)

def test_postgres(dsn: str) -> tuple[bool, str]:
    if not dsn:
        return True, "skipped (no PG_DSN)"
    try:
        import psycopg

        with psycopg.connect(dsn, connect_timeout=5) as conn:
            with conn.cursor() as cur:
                cur.execute("SELECT 1")
        return True, "PostgreSQL connection OK"
    except Exception as exc:
        return False, str(exc)

def test_duckdb_writable(path: str) -> tuple[bool, str]:
    try:
        import duckdb

        db_path = Path(path)
        db_path.parent.mkdir(parents=True, exist_ok=True)
        con = duckdb.connect(str(db_path))
        con.execute("SELECT 1")
        con.close()
        return True, f"DuckDB writable: {db_path.name}"
    except Exception as exc:
        return False, str(exc)

def run_connectivity_checks(values: dict[str, str], *, skip: bool = False) -> dict[str, Any]:
    if skip:
        return {"skipped": True}
    results: dict[str, Any] = {}
    ok, msg = test_socrata(values.get("SOCRATA_APP_TOKEN", ""), values.get("SOCRATA_DOMAIN", DEFAULT_DOMAIN))
    results["socrata"] = {"ok": ok, "message": msg}
    ok, msg = test_postgres(values.get("PG_DSN", ""))
    results["postgres"] = {"ok": ok, "message": msg}
    ok, msg = test_duckdb_writable(values.get("DUCKDB_PATH", "data/local_db/nyc_mission_control.duckdb"))
    results["duckdb"] = {"ok": ok, "message": msg}
    return results

def run_wizard(
    *,
    root: Path | None = None,
    non_interactive: bool = False,
    env_file: Path | None = None,
    skip_checks: bool = False,
    force_profile: bool = False,
) -> dict[str, Any]:
    """Run full setup; returns summary dict."""
    root = root or project_root()
    defaults = _default_answers(root)

    if non_interactive or os.getenv("WIZARD_NONINTERACTIVE") == "1":
        values = _answers_from_env(root)
    else:
        values = _prompt_values(root, defaults)

    ensure_directories(values)
    # Ensure multi-profile folder exists (best-effort; does not force profile layout).
    try:
        prof = (values.get("TOOLKIT_PROFILE") or "default").strip() or "default"
        (root / "config" / "profiles" / prof).mkdir(parents=True, exist_ok=True)
    except Exception:
        pass
    env_path = write_env_file(root, values, env_file)
    profile_path = write_analyst_profile(root, values, force=force_profile)
    checks = run_connectivity_checks(values, skip=skip_checks)

    # Optional: Windows Task Scheduler setup (interactive only)
    if detect_os() == "windows" and not (non_interactive or os.getenv("WIZARD_NONINTERACTIVE") == "1"):
        try:
            click.echo("\n--- Optional: Task Scheduler ---")
            if click.confirm("Create or update a scheduled Analyst Pack run?", default=False):
                cadence = click.prompt(
                    "Schedule cadence",
                    type=click.Choice(["Weekly", "Daily"], case_sensitive=False),
                    default="Weekly",
                    show_default=True,
                )
                day = click.prompt(
                    "Day of week (weekly only)",
                    type=click.Choice(
                        ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
                        case_sensitive=False,
                    ),
                    default="Sunday",
                    show_default=True,
                )
                time_str = click.prompt("Time (HH:mm)", default="23:00", show_default=True)
                task_name = click.prompt("Task name", default="NYC DOT Analyst Pack", show_default=True)

                script = root / "scripts" / "register_scheduled_task.ps1"
                if not script.exists():
                    click.echo(f"Task Scheduler script not found: {script}", err=True)
                else:
                    # Preview first
                    preview_cmd = [
                        "powershell",
                        "-NoProfile",
                        "-ExecutionPolicy",
                        "Bypass",
                        "-File",
                        str(script),
                        "-AppDir",
                        str(root),
                        "-TaskName",
                        task_name,
                        "-ProfilePath",
                        str(Path(values["ANALYST_PROFILE"])),
                        "-Schedule",
                        cadence,
                        "-DayOfWeek",
                        day,
                        "-Time",
                        time_str,
                        "-Preview",
                    ]
                    click.echo("\nPreview:")
                    click.echo("  " + " ".join(preview_cmd))
                    subprocess.run(preview_cmd, check=False, capture_output=False)

                    if click.confirm("Apply this scheduled task now?", default=True):
                        apply_cmd = preview_cmd[:-1]  # drop -Preview
                        subprocess.run(apply_cmd, check=False, capture_output=False)
        except Exception as exc:
            click.echo(f"Task Scheduler setup skipped: {exc}", err=True)

    summary = {
        "root": str(root),
        "os": detect_os(),
        "env_file": str(env_path),
        "analyst_profile": str(profile_path) if profile_path else None,
        "checks": checks,
    }
    return summary

def _print_summary(summary: dict[str, Any]) -> None:
    click.echo("\n--- Setup complete ---")
    click.echo(f"  .env written: {summary['env_file']}")
    if summary.get("analyst_profile"):
        click.echo(f"  Analyst profile: {summary['analyst_profile']}")
    checks = summary.get("checks") or {}
    if checks.get("skipped"):
        click.echo("  Connectivity checks: skipped")
        return
    for name, result in checks.items():
        if not isinstance(result, dict):
            continue
        status = click.style("OK", fg="green") if result.get("ok") else click.style("FAIL", fg="red")
        click.echo(f"  {name}: {status} — {result.get('message', '')}")

@click.command()
@click.option("--non-interactive", is_flag=True, help="Read settings from environment variables")
@click.option("--env-file", type=click.Path(), default=None, help="Path for .env output (default: project .env)")
@click.option("--skip-checks", is_flag=True, help="Skip Socrata/Postgres/DuckDB connectivity tests")
@click.option("--force-profile", is_flag=True, help="Overwrite existing analyst profile YAML")
@click.option("--root", type=click.Path(exists=True, file_okay=False), default=None, help="Project root directory")
def main(non_interactive: bool, env_file: str | None, skip_checks: bool, force_profile: bool, root: str | None) -> None:
    """Interactive NYC DOT Toolkit installation wizard."""
    root_path = Path(root).resolve() if root else project_root()
    env_path = Path(env_file).resolve() if env_file else None
    summary = run_wizard(
        root=root_path,
        non_interactive=non_interactive,
        env_file=env_path,
        skip_checks=skip_checks,
        force_profile=force_profile,
    )
    _print_summary(summary)
    checks = summary.get("checks") or {}
    if not checks.get("skipped"):
        failed = [k for k, v in checks.items() if isinstance(v, dict) and not v.get("ok")]
        if failed and not skip_checks:
            raise SystemExit(1)

if __name__ == "__main__":
    main()
