"""PDF Report Export for DOT Sidewalk Toolkit.

Convert Report objects to PDF using weasyprint (if available) or
a simple HTML-to-PDF fallback. Also supports direct DataFrame-to-PDF
table export.

Example::

    from socrata_toolkit.pdf_reports import report_to_pdf, dataframe_to_pdf

    report_to_pdf(report, "output/report.pdf")
    dataframe_to_pdf(df, "output/data.pdf", title="Construction List")
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Optional

import pandas as pd


def report_to_pdf(report: Any, path: str) -> str:
    """Convert a Report object to PDF.

    Uses weasyprint if available, otherwise saves as HTML.
    """
    html = report.to_html()
    return _html_to_pdf(html, path)


def dataframe_to_pdf(
    df: pd.DataFrame,
    path: str,
    title: str = "Data Report",
    max_rows: int = 500,
) -> str:
    """Export a DataFrame as a styled PDF table."""
    html = _df_to_html(df.head(max_rows), title)
    return _html_to_pdf(html, path)


def _html_to_pdf(html: str, path: str) -> str:
    """Convert HTML to PDF using weasyprint, or save as HTML fallback."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)

    try:
        from weasyprint import HTML
        HTML(string=html).write_pdf(str(p))
        return str(p)
    except ImportError:
        # Fallback: save as HTML
        fallback = p.with_suffix(".html")
        fallback.write_text(html, encoding="utf-8")
        return str(fallback)


def _df_to_html(df: pd.DataFrame, title: str) -> str:
    table_html = df.to_html(index=False, border=0, classes="data-table")
    return f"""<!DOCTYPE html><html><head><meta charset="utf-8"><title>{title}</title>
<style>
body {{ font-family: system-ui, sans-serif; padding: 30px; max-width: 1100px; margin: auto; }}
h1 {{ color: #003366; border-bottom: 2px solid #003366; padding-bottom: 10px; }}
.data-table {{ border-collapse: collapse; width: 100%; font-size: 0.85em; }}
.data-table th {{ background: #003366; color: white; padding: 8px 12px; text-align: left; }}
.data-table td {{ padding: 6px 12px; border-bottom: 1px solid #ddd; }}
.data-table tr:nth-child(even) {{ background: #f8f9fa; }}
.footer {{ margin-top: 30px; font-size: 0.8em; color: #666; }}
</style></head><body>
<h1>{title}</h1>
<p>Rows: {len(df)}</p>
{table_html}
<div class="footer">Generated by NYC DOT Sidewalk Toolkit</div>
</body></html>"""
